// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/fairyhunter13/ai-cv-evaluator/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewJobRepository creates a new instance of JobRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJobRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JobRepository {
	mock := &JobRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JobRepository is an autogenerated mock type for the JobRepository type
type JobRepository struct {
	mock.Mock
}

type JobRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *JobRepository) EXPECT() *JobRepository_Expecter {
	return &JobRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type JobRepository
func (_mock *JobRepository) Count(ctx domain.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type JobRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx domain.Context
func (_e *JobRepository_Expecter) Count(ctx interface{}) *JobRepository_Count_Call {
	return &JobRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *JobRepository_Count_Call) Run(run func(ctx domain.Context)) *JobRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobRepository_Count_Call) Return(n int64, err error) *JobRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *JobRepository_Count_Call) RunAndReturn(run func(ctx domain.Context) (int64, error)) *JobRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByStatus provides a mock function for the type JobRepository
func (_mock *JobRepository) CountByStatus(ctx domain.Context, status domain.JobStatus) (int64, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context, domain.JobStatus) (int64, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Context, domain.JobStatus) int64); ok {
		r0 = returnFunc(ctx, status)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Context, domain.JobStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobRepository_CountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatus'
type JobRepository_CountByStatus_Call struct {
	*mock.Call
}

// CountByStatus is a helper method to define mock.On call
//   - ctx domain.Context
//   - status domain.JobStatus
func (_e *JobRepository_Expecter) CountByStatus(ctx interface{}, status interface{}) *JobRepository_CountByStatus_Call {
	return &JobRepository_CountByStatus_Call{Call: _e.mock.On("CountByStatus", ctx, status)}
}

func (_c *JobRepository_CountByStatus_Call) Run(run func(ctx domain.Context, status domain.JobStatus)) *JobRepository_CountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		var arg1 domain.JobStatus
		if args[1] != nil {
			arg1 = args[1].(domain.JobStatus)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobRepository_CountByStatus_Call) Return(n int64, err error) *JobRepository_CountByStatus_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *JobRepository_CountByStatus_Call) RunAndReturn(run func(ctx domain.Context, status domain.JobStatus) (int64, error)) *JobRepository_CountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type JobRepository
func (_mock *JobRepository) Create(ctx domain.Context, j domain.Job) (string, error) {
	ret := _mock.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context, domain.Job) (string, error)); ok {
		return returnFunc(ctx, j)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Context, domain.Job) string); ok {
		r0 = returnFunc(ctx, j)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Context, domain.Job) error); ok {
		r1 = returnFunc(ctx, j)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type JobRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx domain.Context
//   - j domain.Job
func (_e *JobRepository_Expecter) Create(ctx interface{}, j interface{}) *JobRepository_Create_Call {
	return &JobRepository_Create_Call{Call: _e.mock.On("Create", ctx, j)}
}

func (_c *JobRepository_Create_Call) Run(run func(ctx domain.Context, j domain.Job)) *JobRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		var arg1 domain.Job
		if args[1] != nil {
			arg1 = args[1].(domain.Job)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobRepository_Create_Call) Return(s string, err error) *JobRepository_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *JobRepository_Create_Call) RunAndReturn(run func(ctx domain.Context, j domain.Job) (string, error)) *JobRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdempotencyKey provides a mock function for the type JobRepository
func (_mock *JobRepository) FindByIdempotencyKey(ctx domain.Context, key string) (domain.Job, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdempotencyKey")
	}

	var r0 domain.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context, string) (domain.Job, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Context, string) domain.Job); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(domain.Job)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobRepository_FindByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdempotencyKey'
type JobRepository_FindByIdempotencyKey_Call struct {
	*mock.Call
}

// FindByIdempotencyKey is a helper method to define mock.On call
//   - ctx domain.Context
//   - key string
func (_e *JobRepository_Expecter) FindByIdempotencyKey(ctx interface{}, key interface{}) *JobRepository_FindByIdempotencyKey_Call {
	return &JobRepository_FindByIdempotencyKey_Call{Call: _e.mock.On("FindByIdempotencyKey", ctx, key)}
}

func (_c *JobRepository_FindByIdempotencyKey_Call) Run(run func(ctx domain.Context, key string)) *JobRepository_FindByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobRepository_FindByIdempotencyKey_Call) Return(job domain.Job, err error) *JobRepository_FindByIdempotencyKey_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobRepository_FindByIdempotencyKey_Call) RunAndReturn(run func(ctx domain.Context, key string) (domain.Job, error)) *JobRepository_FindByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type JobRepository
func (_mock *JobRepository) Get(ctx domain.Context, id string) (domain.Job, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context, string) (domain.Job, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Context, string) domain.Job); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Job)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type JobRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx domain.Context
//   - id string
func (_e *JobRepository_Expecter) Get(ctx interface{}, id interface{}) *JobRepository_Get_Call {
	return &JobRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *JobRepository_Get_Call) Run(run func(ctx domain.Context, id string)) *JobRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JobRepository_Get_Call) Return(job domain.Job, err error) *JobRepository_Get_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *JobRepository_Get_Call) RunAndReturn(run func(ctx domain.Context, id string) (domain.Job, error)) *JobRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAverageProcessingTime provides a mock function for the type JobRepository
func (_mock *JobRepository) GetAverageProcessingTime(ctx domain.Context) (float64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAverageProcessingTime")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context) (float64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Context) float64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobRepository_GetAverageProcessingTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAverageProcessingTime'
type JobRepository_GetAverageProcessingTime_Call struct {
	*mock.Call
}

// GetAverageProcessingTime is a helper method to define mock.On call
//   - ctx domain.Context
func (_e *JobRepository_Expecter) GetAverageProcessingTime(ctx interface{}) *JobRepository_GetAverageProcessingTime_Call {
	return &JobRepository_GetAverageProcessingTime_Call{Call: _e.mock.On("GetAverageProcessingTime", ctx)}
}

func (_c *JobRepository_GetAverageProcessingTime_Call) Run(run func(ctx domain.Context)) *JobRepository_GetAverageProcessingTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JobRepository_GetAverageProcessingTime_Call) Return(f float64, err error) *JobRepository_GetAverageProcessingTime_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *JobRepository_GetAverageProcessingTime_Call) RunAndReturn(run func(ctx domain.Context) (float64, error)) *JobRepository_GetAverageProcessingTime_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type JobRepository
func (_mock *JobRepository) List(ctx domain.Context, offset int, limit int) ([]domain.Job, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context, int, int) ([]domain.Job, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Context, int, int) []domain.Job); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JobRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type JobRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx domain.Context
//   - offset int
//   - limit int
func (_e *JobRepository_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *JobRepository_List_Call {
	return &JobRepository_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *JobRepository_List_Call) Run(run func(ctx domain.Context, offset int, limit int)) *JobRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JobRepository_List_Call) Return(jobs []domain.Job, err error) *JobRepository_List_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *JobRepository_List_Call) RunAndReturn(run func(ctx domain.Context, offset int, limit int) ([]domain.Job, error)) *JobRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type JobRepository
func (_mock *JobRepository) UpdateStatus(ctx domain.Context, id string, status domain.JobStatus, errMsg *string) error {
	ret := _mock.Called(ctx, id, status, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context, string, domain.JobStatus, *string) error); ok {
		r0 = returnFunc(ctx, id, status, errMsg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// JobRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type JobRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx domain.Context
//   - id string
//   - status domain.JobStatus
//   - errMsg *string
func (_e *JobRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, errMsg interface{}) *JobRepository_UpdateStatus_Call {
	return &JobRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, errMsg)}
}

func (_c *JobRepository_UpdateStatus_Call) Run(run func(ctx domain.Context, id string, status domain.JobStatus, errMsg *string)) *JobRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.JobStatus
		if args[2] != nil {
			arg2 = args[2].(domain.JobStatus)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *JobRepository_UpdateStatus_Call) Return(err error) *JobRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *JobRepository_UpdateStatus_Call) RunAndReturn(run func(ctx domain.Context, id string, status domain.JobStatus, errMsg *string) error) *JobRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
