// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/fairyhunter13/ai-cv-evaluator/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewTextExtractor creates a new instance of TextExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTextExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TextExtractor {
	mock := &TextExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TextExtractor is an autogenerated mock type for the TextExtractor type
type TextExtractor struct {
	mock.Mock
}

type TextExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *TextExtractor) EXPECT() *TextExtractor_Expecter {
	return &TextExtractor_Expecter{mock: &_m.Mock}
}

// ExtractPath provides a mock function for the type TextExtractor
func (_mock *TextExtractor) ExtractPath(ctx domain.Context, fileName string, path string) (string, error) {
	ret := _mock.Called(ctx, fileName, path)

	if len(ret) == 0 {
		panic("no return value specified for ExtractPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, fileName, path)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Context, string, string) string); ok {
		r0 = returnFunc(ctx, fileName, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Context, string, string) error); ok {
		r1 = returnFunc(ctx, fileName, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TextExtractor_ExtractPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractPath'
type TextExtractor_ExtractPath_Call struct {
	*mock.Call
}

// ExtractPath is a helper method to define mock.On call
//   - ctx domain.Context
//   - fileName string
//   - path string
func (_e *TextExtractor_Expecter) ExtractPath(ctx interface{}, fileName interface{}, path interface{}) *TextExtractor_ExtractPath_Call {
	return &TextExtractor_ExtractPath_Call{Call: _e.mock.On("ExtractPath", ctx, fileName, path)}
}

func (_c *TextExtractor_ExtractPath_Call) Run(run func(ctx domain.Context, fileName string, path string)) *TextExtractor_ExtractPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Context
		if args[0] != nil {
			arg0 = args[0].(domain.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TextExtractor_ExtractPath_Call) Return(s string, err error) *TextExtractor_ExtractPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TextExtractor_ExtractPath_Call) RunAndReturn(run func(ctx domain.Context, fileName string, path string) (string, error)) *TextExtractor_ExtractPath_Call {
	_c.Call.Return(run)
	return _c
}
