# SOPS configuration: standardize recipients and encrypted files
creation_rules:
  # Preferred location for encrypted artifacts (any filename under secrets/)
  - path_regex: '(^|.*/)secrets/.*$'
    key_groups:
      - age:
          - age1pzks4htzmqe2jacn9r076uqvdpgjj8u4cw5vsgxsxj5mlcthmcxqca2ejd

  # Conventional encrypted files: *.sops or *.sops.{yaml,json}
  - path_regex: '(^|.*/).*\.sops(\.(ya?ml|json))?$'
    key_groups:
      - age:
          - age1pzks4htzmqe2jacn9r076uqvdpgjj8u4cw5vsgxsxj5mlcthmcxqca2ejd

  # Fallback: apply age recipient to any file if no rule above matched
  - path_regex: '(^|.*/).+'
    key_groups:
      - age:
          - age1pzks4htzmqe2jacn9r076uqvdpgjj8u4cw5vsgxsxj5mlcthmcxqca2ejd
