# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Require 80% project coverage
  status:
    project:
      default:
        target: 80%
        threshold: 1%  # Allow 1% fluctuation
        if_ci_failed: error
        informational: false  # Make this a required check
    patch:
      default:
        target: 70%  # New code should have at least 70% coverage
        threshold: 5%
        informational: true  # Patch coverage is informational only

# GitHub integration settings
github_checks:
  annotations: true

# Precision of coverage percentage
precision: 2
round: down

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

# Ignore certain paths from coverage
ignore:
  - "test/**/*"
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/mocks/**"
  - "cmd/**"  # Entry points typically have low coverage
  - "internal/adapter/httpserver/static/**"  # Static files
  # Queue/Kafka integration code (requires running Kafka/Redpanda)
  - "internal/adapter/queue/redpanda/dlq_consumer.go"
  - "internal/adapter/queue/redpanda/retry_manager.go"
  - "internal/adapter/queue/redpanda/consumer.go"
  - "internal/adapter/queue/redpanda/producer.go"
  - "internal/adapter/queue/redpanda/evaluation_handler.go"
  - "internal/adapter/queue/redpanda/integrated_evaluation_handler.go"
  # App initialization code (integration/wiring)
  - "internal/app/qdrant.go"
  - "internal/app/router.go"
  # AI client real implementations (require external API calls)
  - "internal/adapter/ai/real/client.go"
  - "internal/adapter/ai/freemodels/wrapper.go"

# Flag management
flags:
  unit:
    paths:
      - "internal/"
      - "pkg/"
    carryforward: true
