// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCollectableRow creates a new instance of MockCollectableRow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollectableRow(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollectableRow {
	mock := &MockCollectableRow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollectableRow is an autogenerated mock type for the CollectableRow type
type MockCollectableRow struct {
	mock.Mock
}

type MockCollectableRow_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollectableRow) EXPECT() *MockCollectableRow_Expecter {
	return &MockCollectableRow_Expecter{mock: &_m.Mock}
}

// FieldDescriptions provides a mock function for the type MockCollectableRow
func (_mock *MockCollectableRow) FieldDescriptions() []pgconn.FieldDescription {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FieldDescriptions")
	}

	var r0 []pgconn.FieldDescription
	if returnFunc, ok := ret.Get(0).(func() []pgconn.FieldDescription); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pgconn.FieldDescription)
		}
	}
	return r0
}

// MockCollectableRow_FieldDescriptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldDescriptions'
type MockCollectableRow_FieldDescriptions_Call struct {
	*mock.Call
}

// FieldDescriptions is a helper method to define mock.On call
func (_e *MockCollectableRow_Expecter) FieldDescriptions() *MockCollectableRow_FieldDescriptions_Call {
	return &MockCollectableRow_FieldDescriptions_Call{Call: _e.mock.On("FieldDescriptions")}
}

func (_c *MockCollectableRow_FieldDescriptions_Call) Run(run func()) *MockCollectableRow_FieldDescriptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectableRow_FieldDescriptions_Call) Return(fieldDescriptions []pgconn.FieldDescription) *MockCollectableRow_FieldDescriptions_Call {
	_c.Call.Return(fieldDescriptions)
	return _c
}

func (_c *MockCollectableRow_FieldDescriptions_Call) RunAndReturn(run func() []pgconn.FieldDescription) *MockCollectableRow_FieldDescriptions_Call {
	_c.Call.Return(run)
	return _c
}

// RawValues provides a mock function for the type MockCollectableRow
func (_mock *MockCollectableRow) RawValues() [][]byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RawValues")
	}

	var r0 [][]byte
	if returnFunc, ok := ret.Get(0).(func() [][]byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	return r0
}

// MockCollectableRow_RawValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RawValues'
type MockCollectableRow_RawValues_Call struct {
	*mock.Call
}

// RawValues is a helper method to define mock.On call
func (_e *MockCollectableRow_Expecter) RawValues() *MockCollectableRow_RawValues_Call {
	return &MockCollectableRow_RawValues_Call{Call: _e.mock.On("RawValues")}
}

func (_c *MockCollectableRow_RawValues_Call) Run(run func()) *MockCollectableRow_RawValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectableRow_RawValues_Call) Return(bytess [][]byte) *MockCollectableRow_RawValues_Call {
	_c.Call.Return(bytess)
	return _c
}

func (_c *MockCollectableRow_RawValues_Call) RunAndReturn(run func() [][]byte) *MockCollectableRow_RawValues_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockCollectableRow
func (_mock *MockCollectableRow) Scan(dest ...any) error {
	var tmpRet mock.Arguments
	if len(dest) > 0 {
		tmpRet = _mock.Called(dest)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...any) error); ok {
		r0 = returnFunc(dest...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollectableRow_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockCollectableRow_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...any
func (_e *MockCollectableRow_Expecter) Scan(dest ...interface{}) *MockCollectableRow_Scan_Call {
	return &MockCollectableRow_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockCollectableRow_Scan_Call) Run(run func(dest ...any)) *MockCollectableRow_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockCollectableRow_Scan_Call) Return(err error) *MockCollectableRow_Scan_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollectableRow_Scan_Call) RunAndReturn(run func(dest ...any) error) *MockCollectableRow_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// Values provides a mock function for the type MockCollectableRow
func (_mock *MockCollectableRow) Values() ([]any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Values")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollectableRow_Values_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Values'
type MockCollectableRow_Values_Call struct {
	*mock.Call
}

// Values is a helper method to define mock.On call
func (_e *MockCollectableRow_Expecter) Values() *MockCollectableRow_Values_Call {
	return &MockCollectableRow_Values_Call{Call: _e.mock.On("Values")}
}

func (_c *MockCollectableRow_Values_Call) Run(run func()) *MockCollectableRow_Values_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollectableRow_Values_Call) Return(vs []any, err error) *MockCollectableRow_Values_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockCollectableRow_Values_Call) RunAndReturn(run func() ([]any, error)) *MockCollectableRow_Values_Call {
	_c.Call.Return(run)
	return _c
}
