// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryRewriter creates a new instance of MockQueryRewriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryRewriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryRewriter {
	mock := &MockQueryRewriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryRewriter is an autogenerated mock type for the QueryRewriter type
type MockQueryRewriter struct {
	mock.Mock
}

type MockQueryRewriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryRewriter) EXPECT() *MockQueryRewriter_Expecter {
	return &MockQueryRewriter_Expecter{mock: &_m.Mock}
}

// RewriteQuery provides a mock function for the type MockQueryRewriter
func (_mock *MockQueryRewriter) RewriteQuery(ctx context.Context, conn *pgx.Conn, sql string, args []any) (string, []any, error) {
	ret := _mock.Called(ctx, conn, sql, args)

	if len(ret) == 0 {
		panic("no return value specified for RewriteQuery")
	}

	var r0 string
	var r1 []any
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.Conn, string, []any) (string, []any, error)); ok {
		return returnFunc(ctx, conn, sql, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.Conn, string, []any) string); ok {
		r0 = returnFunc(ctx, conn, sql, args)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pgx.Conn, string, []any) []any); ok {
		r1 = returnFunc(ctx, conn, sql, args)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]any)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *pgx.Conn, string, []any) error); ok {
		r2 = returnFunc(ctx, conn, sql, args)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQueryRewriter_RewriteQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RewriteQuery'
type MockQueryRewriter_RewriteQuery_Call struct {
	*mock.Call
}

// RewriteQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *pgx.Conn
//   - sql string
//   - args []any
func (_e *MockQueryRewriter_Expecter) RewriteQuery(ctx interface{}, conn interface{}, sql interface{}, args interface{}) *MockQueryRewriter_RewriteQuery_Call {
	return &MockQueryRewriter_RewriteQuery_Call{Call: _e.mock.On("RewriteQuery", ctx, conn, sql, args)}
}

func (_c *MockQueryRewriter_RewriteQuery_Call) Run(run func(ctx context.Context, conn *pgx.Conn, sql string, args []any)) *MockQueryRewriter_RewriteQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Conn
		if args[1] != nil {
			arg1 = args[1].(*pgx.Conn)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		if args[3] != nil {
			arg3 = args[3].([]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueryRewriter_RewriteQuery_Call) Return(newSQL string, newArgs []any, err error) *MockQueryRewriter_RewriteQuery_Call {
	_c.Call.Return(newSQL, newArgs, err)
	return _c
}

func (_c *MockQueryRewriter_RewriteQuery_Call) RunAndReturn(run func(ctx context.Context, conn *pgx.Conn, sql string, args []any) (string, []any, error)) *MockQueryRewriter_RewriteQuery_Call {
	_c.Call.Return(run)
	return _c
}
