// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBatchTracer creates a new instance of MockBatchTracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchTracer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchTracer {
	mock := &MockBatchTracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatchTracer is an autogenerated mock type for the BatchTracer type
type MockBatchTracer struct {
	mock.Mock
}

type MockBatchTracer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchTracer) EXPECT() *MockBatchTracer_Expecter {
	return &MockBatchTracer_Expecter{mock: &_m.Mock}
}

// TraceBatchEnd provides a mock function for the type MockBatchTracer
func (_mock *MockBatchTracer) TraceBatchEnd(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchEndData) {
	_mock.Called(ctx, conn, data)
	return
}

// MockBatchTracer_TraceBatchEnd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TraceBatchEnd'
type MockBatchTracer_TraceBatchEnd_Call struct {
	*mock.Call
}

// TraceBatchEnd is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *pgx.Conn
//   - data pgx.TraceBatchEndData
func (_e *MockBatchTracer_Expecter) TraceBatchEnd(ctx interface{}, conn interface{}, data interface{}) *MockBatchTracer_TraceBatchEnd_Call {
	return &MockBatchTracer_TraceBatchEnd_Call{Call: _e.mock.On("TraceBatchEnd", ctx, conn, data)}
}

func (_c *MockBatchTracer_TraceBatchEnd_Call) Run(run func(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchEndData)) *MockBatchTracer_TraceBatchEnd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Conn
		if args[1] != nil {
			arg1 = args[1].(*pgx.Conn)
		}
		var arg2 pgx.TraceBatchEndData
		if args[2] != nil {
			arg2 = args[2].(pgx.TraceBatchEndData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchTracer_TraceBatchEnd_Call) Return() *MockBatchTracer_TraceBatchEnd_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBatchTracer_TraceBatchEnd_Call) RunAndReturn(run func(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchEndData)) *MockBatchTracer_TraceBatchEnd_Call {
	_c.Run(run)
	return _c
}

// TraceBatchQuery provides a mock function for the type MockBatchTracer
func (_mock *MockBatchTracer) TraceBatchQuery(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchQueryData) {
	_mock.Called(ctx, conn, data)
	return
}

// MockBatchTracer_TraceBatchQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TraceBatchQuery'
type MockBatchTracer_TraceBatchQuery_Call struct {
	*mock.Call
}

// TraceBatchQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *pgx.Conn
//   - data pgx.TraceBatchQueryData
func (_e *MockBatchTracer_Expecter) TraceBatchQuery(ctx interface{}, conn interface{}, data interface{}) *MockBatchTracer_TraceBatchQuery_Call {
	return &MockBatchTracer_TraceBatchQuery_Call{Call: _e.mock.On("TraceBatchQuery", ctx, conn, data)}
}

func (_c *MockBatchTracer_TraceBatchQuery_Call) Run(run func(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchQueryData)) *MockBatchTracer_TraceBatchQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Conn
		if args[1] != nil {
			arg1 = args[1].(*pgx.Conn)
		}
		var arg2 pgx.TraceBatchQueryData
		if args[2] != nil {
			arg2 = args[2].(pgx.TraceBatchQueryData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchTracer_TraceBatchQuery_Call) Return() *MockBatchTracer_TraceBatchQuery_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBatchTracer_TraceBatchQuery_Call) RunAndReturn(run func(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchQueryData)) *MockBatchTracer_TraceBatchQuery_Call {
	_c.Run(run)
	return _c
}

// TraceBatchStart provides a mock function for the type MockBatchTracer
func (_mock *MockBatchTracer) TraceBatchStart(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchStartData) context.Context {
	ret := _mock.Called(ctx, conn, data)

	if len(ret) == 0 {
		panic("no return value specified for TraceBatchStart")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.Conn, pgx.TraceBatchStartData) context.Context); ok {
		r0 = returnFunc(ctx, conn, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockBatchTracer_TraceBatchStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TraceBatchStart'
type MockBatchTracer_TraceBatchStart_Call struct {
	*mock.Call
}

// TraceBatchStart is a helper method to define mock.On call
//   - ctx context.Context
//   - conn *pgx.Conn
//   - data pgx.TraceBatchStartData
func (_e *MockBatchTracer_Expecter) TraceBatchStart(ctx interface{}, conn interface{}, data interface{}) *MockBatchTracer_TraceBatchStart_Call {
	return &MockBatchTracer_TraceBatchStart_Call{Call: _e.mock.On("TraceBatchStart", ctx, conn, data)}
}

func (_c *MockBatchTracer_TraceBatchStart_Call) Run(run func(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchStartData)) *MockBatchTracer_TraceBatchStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Conn
		if args[1] != nil {
			arg1 = args[1].(*pgx.Conn)
		}
		var arg2 pgx.TraceBatchStartData
		if args[2] != nil {
			arg2 = args[2].(pgx.TraceBatchStartData)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchTracer_TraceBatchStart_Call) Return(context1 context.Context) *MockBatchTracer_TraceBatchStart_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockBatchTracer_TraceBatchStart_Call) RunAndReturn(run func(ctx context.Context, conn *pgx.Conn, data pgx.TraceBatchStartData) context.Context) *MockBatchTracer_TraceBatchStart_Call {
	_c.Call.Return(run)
	return _c
}
