server:
    host: ENC[AES256_GCM,data:B9foAPjU/g==,iv:2riXvhBjN7fTifBsSqXZ7a+97ETmieATWctS8nGfFio=,tag:j257JFYaQsMvPYbfzj/IxQ==,type:str]
    port: ENC[AES256_GCM,data:bdJW+A==,iv:v1kWRdHSprU2fDpvuEW+n+zFODgXZBsweu/9IzdCLsQ=,tag:buGzUntzAQsolH+3spEm3Q==,type:int]
default_redirection_url: ENC[AES256_GCM,data:CDhUF5Ln53a7+PMJfzbC83PuOmDqni180btOd/kkzw==,iv:kEUN+XVV+UkN5pZbZV04EOGsyoTJ0hHj59zwb0drVFU=,tag:ax3nbiZnhR5pkm1QJWS1Sg==,type:str]
log:
    level: ENC[AES256_GCM,data:VSxRtQ==,iv:VYDaEQn4OiZ1NvyUaK1AqFsdGY/5UFt/g2w0jYj7c+k=,tag:hswmrcR/HJmDUIC61wen0Q==,type:str]
jwt_secret: ENC[AES256_GCM,data:yqWF8Xe0kuGIG4kNq0ATkz8RN1jGQxr8c0SX1JN/htZS8LFlg3TU/+k=,iv:oyjKGXV0UrQDYKBfWxUyO8k1JerLTDjgIse0g42BCak=,tag:+gSYwZA4Jkx/NbhY+Y4D2Q==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:/XDJO9LEfN5WCMBRIEhdEX7fB9yRCMs3IX8B0Q==,iv:h3TfK3qqoNY3FveprOgoW34dH1Wq1oLZ5QO22YlKQ0g=,tag:NqUhA4rHbqTvwZSpr+aG6Q==,type:str]
    local:
        path: ENC[AES256_GCM,data:C8IGLwMkXdH38Jf4vt5gUAff,iv:vMctIwjgd8NoJmLpKat/zN2OvkpSaH2wmEeQqwY1Oas=,tag:4kLVJO/7Kki+r7U/meQn5A==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:CHQv17l3bH1XD4lgwjjzi24nzHKPq3ZM,iv:CJgalavOg+9Qt8TisdZQg8e/fOf4aReY4oKIEkY74/A=,tag:PTcTN+88oVUI/UhKfaMbDQ==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:moNd8T+R3sS6P6ZUgHm2ZYqVG39c2Vs/zE8=,iv:Kg4pUS8Fp9et4OD2JDRKj5NSF+EsG5L8P/nEoDRYFH0=,tag:uoSo6vBMVGmr1SDLzz6akw==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:DN6ZVvGxm8xl3w==,iv:RiSJrF4fPBBiMOvjdl85J27UprduYDDNlHAeb9chmtQ=,tag:wWXzYJ3WmqjwYkOuTLQHtg==,type:str]
    networks:
        - name: ENC[AES256_GCM,data:h58wbWr96qw=,iv:Ws4j3YMNDvEsIoyeozhcUCBODVOzBrDQ8mutMQAaq+8=,tag:LoSeP5tN2MMPqFM3bz9IUg==,type:str]
          networks:
            - ENC[AES256_GCM,data:whbzbLrAZbZS3A==,iv:wlRngEXdjvWMMuIdzbpGAfaC7uKtOAaVip3SPFvzhJU=,tag:/2uOwqiLcvhBV7MMljDxjg==,type:str]
            - ENC[AES256_GCM,data:5vzi3HwBMBcgaO749g==,iv:HIaLZE3tDjNfQIVc88RvI+ANFfrvhsIEM7ojFNLT3JY=,tag:SW1CuIz+WbSkE/uTIcH/QA==,type:str]
            - ENC[AES256_GCM,data:Uek4mCCL3h1AH3ghS38=,iv:hf82i6jYGrkseVm5Q9OzAkyzDfGBfmJU7MtM3AHpkTs=,tag:KFcoz4NXNrD0ONOOTgv/XQ==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:lTPWoBjGLVsEAJ93oDMkmpI0xs72MGyG,iv:7m8m3UWRLmfynH18qIQPl+1IlVuifmLuktvUxixbKSY=,tag:qrYJagfLvdd5D5cOkBROYg==,type:str]
          policy: ENC[AES256_GCM,data:arImIe//,iv:Ywa6liVXXqt7sqekXoRdqwVCLCxef/JGroILhcuRvKA=,tag:OZv5eviWfIIsFuZIYDZA9w==,type:str]
session:
    name: ENC[AES256_GCM,data:cQkZymtoVwgmeNvlnM7hug==,iv:3eV4+ur/LIbDFfbHwaT3YRf4Js8a8/rWD2zN0fYUfOo=,tag:t/IIehH6OJw2fvhz81DrIg==,type:str]
    secret: ENC[AES256_GCM,data:D7y81ZHFRe4295C+Vzs3tsxJ67pPegJzgx7fEhqwsz8gGleCwVhKMVuwokLWba0=,iv:UHayCbqzli+zD+I70AtZJXW741D/Et5DF2GLGdC8Gqo=,tag:/mhezuEjew0MwVas3EqTHg==,type:str]
    expiration: ENC[AES256_GCM,data:2DUxdQ==,iv:Bz+I8PuJTbdpf9pvGQTb2jGYf6ItSQku17zbsaOdVaQ=,tag:cvvouqYFYIbkpm2l4tZl7A==,type:int]
    inactivity: ENC[AES256_GCM,data:j2GS,iv:rwaLjOlw0NWn+t1CrVIMNNpzAIqtNVyvudqQ5aS1hf8=,tag:d1aeICAO/zoO0RxslAstNQ==,type:int]
    domain: ENC[AES256_GCM,data:VnqvA1AeZVS0DjkVTxDJVvyK3A+9Zg==,iv:emW8qmn35v+lXXIFDSX2epbFUrSERwxytEzyiI4TPnw=,tag:POVdwCFQY42PMVnWKc6zmQ==,type:str]
    same_site: ENC[AES256_GCM,data:cPFX,iv:JwolXhvyVUY/DLQZ4e9o9w0ycv1oh/e836dSG/Z/W0I=,tag:HNZi233oCUUmfwQO1Y2ZNQ==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:4ApS,iv:SSRjZMdhXBW9s9/oSMtqEUzBuex7xdy+0/HsHsOCraQ=,tag:nHO0YiHbx5DVMGF2US1VrQ==,type:int]
    find_time: ENC[AES256_GCM,data:nA+2,iv:lodAsTbG6bv3xzg91Ar8bBAALPvgT1rV+bgVVsEn4ps=,tag:ax3okOuIo7zek9GSGLhpkw==,type:int]
    ban_time: ENC[AES256_GCM,data:kgrG,iv:WiALof4qullndRarlhtyIuwksHg7pCHB/wZIl6dm9Xs=,tag:67GmqObSqPipgPHtWoIRvA==,type:int]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:ux6xgl6ryBUb3ezTYD0Pdd87zWXtD8ExLbQE3hGiYGtUm6ZH,iv:4CTQ+dZXpC+GfjZhlaUEwb7CL5U1MKxFZAcbAMXZF1Y=,tag:m2afc4ociuL7YrTxccJ8+g==,type:str]
        issuer_private_key_file: ENC[AES256_GCM,data:OGo6qbwpLzSBDBFkAlIN+g==,iv:fb4ppwUuLbX9y5F1NNM2debXDLGDNtCICa5rVlCtCXQ=,tag:vVtUImjbYi2u2EGVRFjA0A==,type:str]
        clients:
            - id: ENC[AES256_GCM,data:qxJKy98oOCQcMRVc,iv:tLH4/Jj4o2p9MUyahIlgaq06WnnyK33InlbByb1jgv8=,tag:fa++fRMy5eG+Ps4xilZ7JQ==,type:str]
              description: ENC[AES256_GCM,data:vQJztI033v/9st6a,iv:YAD7YvSi38wLiC/gUgLoLcr9vXX8lN5R/F3I3HItHg4=,tag:xsm3Eo0oGvvC00OWtenrrA==,type:str]
              secret: ENC[AES256_GCM,data:loPDrWuV9pce1iqMZ/cLx+NgRhFzULUAHKA18xWZTWdahKFBVgqL2kj42lfQ86MgA3SU+TS0/8WxJp0c9XHa+SFQGByJjmkt77D3ggvpxY5n0AXDsADAP3HuHYbrsZDIBHrnLalDuu3cE+kpE0eU6SCzEe8PgDsJ+yoCOZPMW2mzqfM=,iv:ep4W8cYp+mnq0hw8Vif87S6ku6QmiPD/NeE1hbcUUnw=,tag:1GIqMR6cc6LxN5W/9F7wDA==,type:str]
              public: ENC[AES256_GCM,data:7vkzm8k=,iv:GH8CNrPlmuI+qIjUaXYAh28JwngtYVtXVBam22sx5w4=,tag:aCTEXQhPq5woPBLE2OsIyg==,type:bool]
              consent_mode: ENC[AES256_GCM,data:s2gKgwLXDUs=,iv:lZQAWu2uqEk9U75qPEzxb1XX1uEmvBDT7zKWW/AC7G8=,tag:aOpZ9Q6cu12KKsW1EWMn6Q==,type:str]
              redirect_uris:
                - ENC[AES256_GCM,data:cbmpp/G9eFu2Vjkm6sBrssXbsMX4961HglKxMoGr0UT4LZ1szTyqY6oAqcdisg==,iv:FfPoLagWN3DEkVHWk8iA3Og+548KNPmKMTRp/25eRxA=,tag:d5+n5dWT55/VdNYgqhE9kw==,type:str]
                - ENC[AES256_GCM,data:pL8gujElbLJDRkVaOIsii/pxyjRK5cHXCxShVJ7HYh4DeABNIRL6uKcTAzTJc3+SHRWrV6G6Kl0=,iv:Lzr3SOKHDxFk19pk5slDLCBDOQkF/IXlynTBwxiOsEA=,tag:EaCLoigfIwSD2630hGcaLg==,type:str]
              scopes:
                - ENC[AES256_GCM,data:FjuGM9Fl,iv:iXG9ObbZ/LfKgoFScWmuGvjTzmKKkaLmvMgEN8CFfsA=,tag:g3PS2WceDd576/Owm2Rwvw==,type:str]
                - ENC[AES256_GCM,data:6UJzR2kLiw==,iv:69HyAXsNuF4anNHSNaya0KdQRiLjj1a/fi8YSu9P7uI=,tag:vHQglSNsvCtCR2u6ZQAovg==,type:str]
                - ENC[AES256_GCM,data:Kzi21q6S,iv:+PszgFVoJ0CUxW6XREKuWsmpGfL8JvBlI4JkSsubAW4=,tag:sSDO27EounACTaU2aFFy0Q==,type:str]
                - ENC[AES256_GCM,data:x1j7qKo=,iv:sCncia1Gdryi32gRLyt/6ngCqz0yKp8A7eENLN3qrOE=,tag:BqRB+TsoArCeHWVnrJyASw==,type:str]
              userinfo_signing_algorithm: ENC[AES256_GCM,data:wnSmXg==,iv:fdBJQ1kzV23d6uQ5niroKOR/RZhHFnPZpi4IBQHUJzI=,tag:tm40SWFBipqQYnOwJvCEGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19txs0a7xl89m2f0983fn0k3szj78n3tcjv8gddkvzk72r3fwsa3ssw0clq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQlhKeVdvZnljMjRxaTJN
            WEJkZ21lUzNDUU9xQzF5eUhMQU95ZjBmbGs4CmhkaHRSdHBoTlFYWW5xQnp2QXlO
            UnNTSlZ1bm0vazRQTWdaSGhRM2MveEEKLS0tIHVBSlZ0YU85RTJFeG5UWS9VK3FL
            SitERzJGbWtRaUdxa0ZUZEs1ck9iQ3MKFjQ1dSUzGXvLXuzLjSZ4XCWErI3FO5xe
            52xEoY6YCSabiVhqvP2sEIDfxthgpB/duY9yGEUfQJKPpWDWfCBDCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T13:37:20Z"
    mac: ENC[AES256_GCM,data:tXznF99GIOjq18N89VYBGH8CfPtusYpn1bG6hN7EvPES6U0uETu1/g8xo3Z+Zt7eIJ3lGjVoTiXUmH9vDPb+UDUlRLFpTjg5npTQgGrERARFf69BOS2k77Md6aTkkqA95fJnu7jTdTlgE9QU8OzffOC4wDZ5rRIscOhs7RxigYk=,iv:X4fAdnu0w6g0ycNMuWVpxQhTucJHx0oPk6pETuNW71o=,tag:9gO+LdCfKkWya3bT/HTIHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.11.0
