server:
    host: ENC[AES256_GCM,data:VL0EDwiVIQ==,iv:cG42JB63l2zVw+HxLKIWuQl7kKnrK+mgXkgvKT4s3Bo=,tag:sUTtXb5EOma+qGj+uhOe/A==,type:str]
    port: ENC[AES256_GCM,data:ZcwpDQ==,iv:cibBXyzbJXxoE+ogvfhNxmA7iBbzRc9hTHiLWNpYtF4=,tag:MULwdvrQFHaxCHxs/okL0g==,type:int]
default_redirection_url: ENC[AES256_GCM,data:aMTEiDNbADr5t9iiUoev/mAQkh9FMA==,iv:9cbVkmhtL6mrqJHUIS2RhBugLNY+qrksHbNuHGJzpHg=,tag:mA+AnMjc4c3d8wNEc9VCvg==,type:str]
log:
    level: ENC[AES256_GCM,data:Q0BpBA==,iv:sjCVzvnEAn4INa2X5U9WhMXFqNatmyUV0S3NyQSNVRM=,tag:AtqBgMeF6LgMCOhjuvh6IQ==,type:str]
jwt_secret: ENC[AES256_GCM,data:agxQFuafMQBZwhlgn8si3ASx/jW8dTjw0r8U3dfbSHGQGxeEN60tJX1ekn3CGHi5zjVrlzw97iNolLFtfas1yQ==,iv:Gq1yQ05xdyp5PYZc/PeNR0MHHms1tNxmg+yb9G8KyN4=,tag:Q0EDbUYP4L0HSlPIPeUKNg==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:Qcs+c+rS6A6gtms1K852B4lLTLXZRw4ktFDLqNJix2cVYJODAulnDL6kcsr07rYF1VY0XH1YtyrexN9kHUJ92g==,iv:vCB0eHInRUR/Eg9rtdEGAVUykNczgM6nqvpDr9/oX9g=,tag:AHUBs9+l43UgVCJoimD2CQ==,type:str]
    local:
        path: ENC[AES256_GCM,data:bNdEYJrHTQkl9ddzRLmmL6pF,iv:552dttDz50XZ9WaQ2PSUmNaNP0oyuM11Sg/ADUg5X4g=,tag:O55U+9au5XAJALj4zm9KJg==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:CLGbcOPdKKmopR4xJpfTp9Rkl5bCDn3q,iv:kwTGhdkj/UXVAePBnH7QEEX0/WFF5sDUGcyh5TmwDOI=,tag:sTsjCz8vkQYa/UmL6yf92g==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:d/lbDy9GyaJk5NJ+foQIHkcyoe9Uilqq0ZI=,iv:xqLrfyYLRbRRdsl8GHe4VYkxg2p6NKRAPSxU7xoXfuE=,tag:VbLdgcrYlWwsMmhVExFqQA==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:/ilpHlSVbcymKA==,iv:gJxU5tSWSAdFBGlL5T+zAYpBrwjvG71nrt/McB2mds8=,tag:1aas7YPj3iVDk8Qa3ufYFA==,type:str]
    networks:
        - name: ENC[AES256_GCM,data:vQANzJpfCmE=,iv:DHkgebEZR6d0h5eRVx/SXJl3Dvmyt+jJv3j5+re/kIU=,tag:KBgoEBHcwbJX68X70cvp6A==,type:str]
          networks:
            - ENC[AES256_GCM,data:kS1Mze2yMWMPTw==,iv:gdIW2akMHBz1WUHe0U3C1KLo6RwRfHnDbYjSY3lb5E0=,tag:Pdu6PHVQLmUoD45vGmILfQ==,type:str]
            - ENC[AES256_GCM,data:QoUWoRiPq9M37+KMnA==,iv:jH04/W8ASm/oJ0Zm6+AfxIAzjOT6gZ/VEoRKDNX8ORM=,tag:wmo3toIgNwqNcUMwF4LkpQ==,type:str]
            - ENC[AES256_GCM,data:qIU2d8jDSoPhQapwrp8=,iv:CvX8qsvB5rFqj0ULMFlunm7H/vkmToFfcFxKtOYGyFU=,tag:NuUOS25KeVhqctBmn5BO2w==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:GDDcjTxsqdIt,iv:qPSKYyEKKLp6D2ZMUBXGaM8xoyPMy2MYvuZQUHzAE+8=,tag:pByQ1Fhr/WMNU0PWqohlMw==,type:str]
          policy: ENC[AES256_GCM,data:lYetG5rb,iv:Pw1agxGLFKwIIHj2vlnnS5jbdLybU89X63tr4gfUAlc=,tag:/XoiGJFcqE8QroX+qhI3Wg==,type:str]
        - domain: ENC[AES256_GCM,data:rhEk1PzXdjh13xE=,iv:X0Ov8gPsO0UNOzqRC1JsepRqq8DpKF0z/rtyoAGiFtQ=,tag:V60tFYshmqIh5dyLgAVYBA==,type:str]
          policy: ENC[AES256_GCM,data:lYetG5rb,iv:Pw1agxGLFKwIIHj2vlnnS5jbdLybU89X63tr4gfUAlc=,tag:/XoiGJFcqE8QroX+qhI3Wg==,type:str]
session:
    name: ENC[AES256_GCM,data:LrfijpJZDcVB2rGVEWax2A==,iv:rwhDkSWE3UcbBY+x3qFudmdLWA2Mx3Lx10LEUa+eZ7g=,tag:XRgHAgGSMpHnYwyIPcs77w==,type:str]
    secret: ENC[AES256_GCM,data:ijSRyLCpRVQx7M4dKZeeWK7oR9mtZJMBluVGdCZOJWywph4zIULSicxoCarSXnj0qIoM9Mnl6tkBYOkfnHJhTg==,iv:4nhQd+ei6mMtkj16/QptdpQ5w5IMPVRFbEDvYETzfqc=,tag:3ekZZUXwQA7w3eKVl3iArg==,type:str]
    expiration: ENC[AES256_GCM,data:LqQDqw==,iv:sq44DJVd1l1hmB/1WWUBD8gWwwNpdr7mHAOwVA8hPqI=,tag:GWr8C7oW/oV5LREvSCJIYA==,type:int]
    inactivity: ENC[AES256_GCM,data:qRx9,iv:boO0//6XwPtll6GLlET6LCquzyq5A0Ji5Ds7v+jw9M0=,tag:vX/v+u6kXAX2VjXC+rM2lg==,type:int]
    domain: ENC[AES256_GCM,data:OecLbzBjtfPD,iv:5TLTVKzcOS5u6PSGv2H4NzUMVzhlwa0nieGWZ9MfhpQ=,tag:Fsd4dnAbD3OC0V1kWtVwsA==,type:str]
    same_site: ENC[AES256_GCM,data:CTec,iv:jeVAF7P/8bjgNIdvzq2hmDe3ApOxZpw1QmTshaIwb8I=,tag:l5zmDLd/TGRIGzzSSwZr1g==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:tXCD,iv:VHKpvJkaZN8V89/yePSHkq/c3kU+pQxjArXgP69EI80=,tag:sEceFrgFpNMgxZaZaxs9VA==,type:int]
    find_time: ENC[AES256_GCM,data:mN9+,iv:CI0zpx5fKTOVkWHw84aKzA9d8WGZqiPY/HSnlIgiIR8=,tag:IZoYS4ADWM63kDT1G5R+Rg==,type:int]
    ban_time: ENC[AES256_GCM,data:qXHe,iv:JJBUk3o3NSDTcqIsaRhleMpsLNTuoAj4K8hY7GdgbAk=,tag:veB4qXUJ0su6WeAyFcoaqw==,type:int]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:dtkkEomMJGyy9CxVs2Lab9tVqC39+a6/hfSS+Ci0aF+6Ptq2/IBB8V40ZaUPUW3w0hOh1aunvJLESbLx4wDeuA==,iv:/A4RSmxM6EFzj8SGdRh16iVXDPJRKGCn/tNDgjwA10A=,tag:tZ5UY4A/Uuzyg1noFryDxg==,type:str]
        issuer_private_key: ENC[AES256_GCM,data:k4NDtgrpuSigIqO+fP5JlbU59npREWHlvZVnq1QI79sI9hDUS/aF4ViD30JMcv9dlvdDxF0DI/rJeWtMFvKK4lFHARjRDAxT1dKY79/pUlSYMKvOwZprV7ziH0JvkoY4oKUVsb0BgHpls5FRoy7F2U464lKGRbpkOp6y9e1s0AElb/at7/Br8EyA2zzDshAqBT/kFwbGIYumENouCoVZOEWHl0BN8BZy+i0c/i4Iy8Jqke0Q9WSARCpVXOLJgQ4BnqDB5Tr4E4nlHpHZRQ6jmoyG4OMB9XCeMtSFQWKIPzuYKblVWbHlirAx8Qi1nxlxlOSqFEujlezdi4nWd+NK1bXBMgZwvmgHXsmihvEbsPJy6f7oU3R8rb8CtDcIWogdZ1cDg9XyzfCwmWTWTZFdnMtHH7xbNl2jspVF0kq/HFK8aqdXf0yKIoud6uk1nBqe3lO3+W2iOmSNg9N+BRq6oEZo8rTHuGh6jVjaPm7mQYcol2XQXJw7wqKG+HX6eOM07BDXMm1GpdGExK4P8Iqq8dp+F4wTTz3AnzPZjHRLQQsPKsuVZqSj7ZVXaxW+MO9cfe3oPhMIkOohhAWD69+EyldzNbxshHWp8thDohu6+CFFmjnItugoOp1qMxEy7D1XN8gHL9FazF5kioi7wnRhDxae4xLqJXDE4Q+e93zFUCSifeBWJGNlt9uAe9fap4Wo52YRakF+y0ABlKBfkjrBxtMAcfVBO6y3w7uW4njzRt5BswmWBKAmWhxkbQCP72iRKjzcq3lu/I8URgAwYFazGkzFqnh/ZWjFJ+sWmlnnm0KZpfoong+DXDH3xKxZACAkm3glUMBLTbqU0O6pSJIafHTkKsblwshcNCYW5M9nQ46uNR4uTXJhUbXaHXNkyKxAp1Z5RvT10O7ly0ZenGgDLZzxwHKS9/tn058996MHYyYCBgG/srVaZiIXaggL3/V1uKIeCqsNxTuC/BCdeKkaB2LGVy1OFrAgio6KX2D8x89IVbucAn8vX8WM/kJnRZw6PM9sTOoR1ficOApTEfNLH/8s2JzOikSID0+ZzpZ3K1/4P6SMqcUWrnHSNMBUc9brcbCwRrfsfrAsdDcA6TRhgSJ9BO0JwTfoMcDIZtv7MUUGk5GgwMgJztDn2kvs+GvcX8aOGTeLS6O/QILn/3pXNIOJD+sK91/oqSojTsc80XM80GqDHx2OFtS5w7mqVrDacMsILcvWfuFP0rviXRBP22Rg2VfXe6Hw5j4grPg41ha6x6R938FCdUhPD5kedVpjljOhtEa7gcv1bE6zxT7hZ+lUZ6TI7PN9T41WmPZR4fQ8Wk7uVUfHBG1fFEvPUPuA89AorrGsqlxUYm3mDD8MORlHGdu1nQSIFGFtCQfFHUc2hUgo7dwdrOS8iVZK+teo/cbmFl6isW1lTTdZMM6RMiDpXxtJ9sdsxBIYBiwnhfO9oLhJeTIrJu0UkAdg5zF/teYZDC3WimKmZVZ58U65vWulGJ8kFzUGI03ApnG8LSrJxTiV6Mpdn0rxGXmTYgwRWxUJ3N4bA1jLEZRFYHWFZaKIyJJgQnsKjbypW6shHDaf0uJt2fhcu3ia665uI86ivMtQpSjZBAF4F6s+0ySweoAPN5eLqqMGLC2R1BC3fe89ui6fUFMJLXkQ/pR2OB/djjPYhAofsspnbg7gc3F2XdCfMGN3L9UVtKYrpUZOQsYgmsEWy3y2xLvcYtGagOtH3VRkMmHFGxNaTFUwTillOss5/dZPg+uJWCXITj7BED6xXq5w6IKOs67XQI8WH5Qw0aq1+o0xR2lsmW+30W0MktuVLxqRimibVtU0XsbVgWQ0eeCfNENVoq8S7bjmKTcD4DeQ7P31DNlsKaqxjGmBc/uglMHRDYIzdWALyo2swGnXxTilB9hf+i2J4aqtqW68n5GHF4HR3CIRUit8xX8WVxTa/nG0zfUPEM1KrvbuOzWKaHyNw4sFcklB5YbaKlXp9FDIlA5NsFmf3czJWVlGcbCwggK5fFSw1jogzAwbMFR7Twluh2Ljq2Fi3fpPdCDAQTS4eoVS174GfT0hjVjE3dm/r1CwzVLvQplDTtGHSdAgoJfMSbYRJ+rvHqh4DOXX2YnoKl8qstUZ7CL7p4s28iDfQwGXD+XKcRLh6pGk276/0ek/2Yudu0dAabrFAmFX6k5eNQszzWyjDUDGk/GIzUpwOI3KoTWyPObOZ1wE3g/9c40bNZHycILClGkgp4oUl1m4rpSi3iwXISVY7Y8HGHfAkjK0wVS/,iv:itbH/P3Wxm4PkGDF+f9TjavtkHy+I2AxG58T2V6VLek=,tag:9hHggsBcJhfg1L6RQJADyw==,type:str]
        clients:
            - id: ENC[AES256_GCM,data:i+eXZXTR4wLiRbjU,iv:NI7u/pwSzkhc+QB652XnPm+cWNqP9qRmXJ0v2XlNY4E=,tag:HQummsfhR9cfNnerch3IrA==,type:str]
              description: ENC[AES256_GCM,data:ZsZcSIUZEhRaQnLh,iv:dFAEOHxY+mbUFRpW8Cy8IHk44jqssBDNK///z/ehOyY=,tag:YdxhkMVLO/VkBvYsbuFUMQ==,type:str]
              secret: ENC[AES256_GCM,data:qDkbLvJHL9Kv4WaCKSIcyRyeaNnJYBKSPU9lw6u8PPr3MY/s5Wx5I5xwIgbiOXA3RTiZuW0FNerAIp0sgq9pFJHd79Cbpq7mbcAtEMXLmuYdIqDzBGiiJGO5WjpxVHKMnTTwxToP88AIRHlrruvfUlQ8j46rJwtR4NRSZtuEv48Qv6w=,iv:fcXNWWdvCVfUSG/cMYNDvNepSXF6BaHD5CVpno7L5dk=,tag:dLZ5MvG5jsJ6yDviQiPL/Q==,type:str]
              public: ENC[AES256_GCM,data:eUxsrsY=,iv:PuQMsWaL6HTLzC2h2LhBFi2flYFxOQXUNT1HOB++kiY=,tag:P8iHga+axFD9LjGXIskA9g==,type:bool]
              authorization_policy: ENC[AES256_GCM,data:QpjQMsQmmbx4Rw==,iv:3TaqOGzAXpJe7DusYjqn8czhbDHCcgEdcL+WoaHYgvY=,tag:55hhJDWz1loQhSzTJFl4qQ==,type:str]
              consent_mode: ENC[AES256_GCM,data:WXbHfDy4hx8=,iv:PFwM3BmYvrnQv7qFeIKkHEC7tCMNAbc23aQiK9VunZY=,tag:BYsFll7wx5oO+7st55gLhw==,type:str]
              redirect_uris:
                - ENC[AES256_GCM,data:7hWbrDwzL/4dfZnHf7V8jM6u5wzC000GuhGA0zNNNsKXTTH5eA==,iv:SOTW/mFA0mj/vHu+AUyhSmjZG2XqTbrosCnMyDWxp08=,tag:ZKxmIR9pMeIikH7JagKr2Q==,type:str]
              scopes:
                - ENC[AES256_GCM,data:bgbhBxcE,iv:C1mhFOswX3Es9xXFJxrgzwsVJOwb9cEXEV80OHN10Mo=,tag:udgecDFuD2BLpOEzkSqc5g==,type:str]
                - ENC[AES256_GCM,data:gK0QBPIagw==,iv:9wbw2gqrbwiOP8vEqigg7BXIwj5k+LjxUiFbizLdhmA=,tag:tDbbGql0OY+cu9m8BuGdfg==,type:str]
                - ENC[AES256_GCM,data:uhGu2Vaf,iv:oYUAld+ygiQUyNBmXYLNCl3kGSEiI9Jgj/w/600p96U=,tag:CZzcQRgelFr+b3sXnJ5G0w==,type:str]
                - ENC[AES256_GCM,data:rNQstf4=,iv:HbBYvWPq+UrGQvQCUJTSdsjQ/BHW3rzxQ7wnoBeXmCE=,tag:j5cfCR3Ph763Y2RpBK556Q==,type:str]
              userinfo_signing_algorithm: ENC[AES256_GCM,data:QPl2bw==,iv:XJ77dKx8l2b8A4e3WKrmrVwyhycm71c3N4NNoUiAtLA=,tag:J0i+99UX67QutYyA58exfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19txs0a7xl89m2f0983fn0k3szj78n3tcjv8gddkvzk72r3fwsa3ssw0clq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQUtDdzdEQlRNQURXWGYw
            Y204MFJ0Ym1sQzZuU1VSZmZHRjE0MldQY2hvCmNRRXczS1NqSlhCZFZtZ3NPV3lK
            Y1RGT25sWTFoeTE3dXZHSWJPbi80L2MKLS0tIFhLSElkUXpkS09CZUdJWmpVTHBB
            SWEyOE5UYnNPUThveElrSGxVelpmUXcKL0wGTh+/kp4IgHMRUpW9TFE57SbPEJfm
            kh5PAtdulCKrOmeSyxGRdYHSaM69r6OUvbQQ4nDa2pdqjrbPhwLFTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18y6d3jk79rvl27k6ux4fprk45rvfgxyux4a9wxjdsz3cstvecv0qcm90j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYlNoVWxNcXJCNGlvUC9h
            MnJocHppSmxqSjZPVkNtZ1FocVk1VlcyVEVjCnozTnhkZFZNRmMyNXdNNjRYQndX
            UGNlb1A2NUxCWWJ4aTZZREQzNklZWmMKLS0tIHNZS0ZGeldpVDBQMy8yMVBvRUVa
            SFBmWU51emhmL1dUdEZnVkk3MFhXSmcKM4tq+dak6c+I1o0aiM0jIf4yemL4ZBfY
            ws2BA7HYAqa8zc2WxkJKmE+qUfB9ACkv7mCsaE5fwkmvLV8qfsp7ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T01:50:19Z"
    mac: ENC[AES256_GCM,data:Zz8+A/s3kKOu/nraMNqIb9v2eyZeMhbsY9e5MlDr9zJ0nYjgoKL/yrC7KeiLvLuhmBcM535shDCycDY3hbHHplCB7kKD+Gv7RZH/JzKqL4tmAFsT/EQj/RTBRbHbIzzadxEBLQPzWcSgPKfrHuKu9D26JCkq5oelb2GLfAkaf6M=,iv:fVM4MjOWtsYOBYkoXUEx8AVVTEpRoZHHToc4U0zBMs0=,tag:XyfKiHASUb4Pe+R8/19LqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
