server:
    host: ENC[AES256_GCM,data:xg3sqxDhNQ==,iv:y+Ezm0BUY28n6Uj477N8bsnvihdadCP5bNgblCHhIdA=,tag:IWFFhEcTwtSzLK5nytPQ/Q==,type:str]
    port: ENC[AES256_GCM,data:yaPjHw==,iv:bieBF9E4cL2sH2yibqUGvZ8jdJ+524Ltz09WJRD/ZyI=,tag:zGEbRRylM4qeG8OgdNrTdQ==,type:int]
default_redirection_url: ENC[AES256_GCM,data:aTB8n2sINSQB2aXYyfam9JzZfFbdTw==,iv:x/GKKURXeHs8k2/TIDryodHEj9U3/snzXsbiSCSqcGc=,tag:iWO27PWGd9Gr+uFq63RKGA==,type:str]
log:
    level: ENC[AES256_GCM,data:RMlRDw==,iv:8nvZIJ9w6ZSqwkaN0JeT1pi79TTWG/ugTBr/J0H6yl4=,tag:0Ey7SCz2r+eiU440Xi+UCQ==,type:str]
jwt_secret: ENC[AES256_GCM,data:f9vA7QH+EQumylQccU1n0KIm435VWE5Hapftp+N1itst85VpaemFsNo=,iv:mcU/doUKb6uhQoL8AqwlpN9P35hZ1n6n+LkGGjtXQqg=,tag:SM1LUl/U4JprX/xUW41ocQ==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:m/143/8MDYzuanT74VfkgoExPYhuw5rTnRI3QA==,iv:c+cMe50gOd9wOUZSonUJOV+xsONcOknlvj2VCQIgNNQ=,tag:IpkPTHvLn14UV8eywcpKnA==,type:str]
    local:
        path: ENC[AES256_GCM,data:j9bbBNvX+N2Vlu/zCAHxSWlG,iv:AUanMA2iZZLzlr5drF8Zec4iRJ7L6nDjOq+Uu+qYszI=,tag:XSkeYwcvouCQVCMTU8Jgkw==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:JOKQnv6QzN5yQ0D9waX82uptMunaNF7h,iv:Anbcus+Ulz29oEHRd2bfV2HwLxdEYIFcn3Q0EsdkwZU=,tag:1oMd60yTYl9eJzUCEEt42A==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:m6NO4bGGLIhfHJKRKKYSHz3+/CLsF/IMwJg=,iv:8Pibh08+3FQDOYCs4+EFnQVPLkvf2JyeM9EfxylDhYQ=,tag:39EiussF3+KLcCdWoRISUQ==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:A3BhElnVn9MSNg==,iv:Os/XgpZWU8lwf84p+MZw6RGcgAeS/kT5tDR7hG6yJ9g=,tag:onPuSEKtJCJxB1FCm8cUrw==,type:str]
    networks:
        - name: ENC[AES256_GCM,data:fbG7i0pmsc0=,iv:tXKxmGIlRseyROojdm4S+hf4cQLKkxk+mie7DPHLKRU=,tag:iUe0jQ51WzLuJTPvKfHIhQ==,type:str]
          networks:
            - ENC[AES256_GCM,data:4spj8DOurf5snQ==,iv:YRfoLuGYK7h4l6CX2YbJ6Dsijgz71nPNZA+S6MHseW4=,tag:YmngKn8BS+nxlyFequl9zg==,type:str]
            - ENC[AES256_GCM,data:emyrdY90QtaXP0XZlQ==,iv:xVNLspixZwmKb2CT+NRcvvpFb+syFYhevkqmAlR2fNo=,tag:yDdokUmO0XyfRM7VNtT4kA==,type:str]
            - ENC[AES256_GCM,data:t6jN3tOHDCwmiw1D0oc=,iv:VdkVciF7QIwHt6EXmPyCaKS3sL88xVk0mUQbC/NIw1Q=,tag:Kq71qsoSJeW0n/tAuzpifg==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:ervZO4aRqVCt,iv:biuoKszVnZP0Vwp/azewS2iHn+O1poOpzPzfRpOKvVU=,tag:sJqnBMzMwOjzYXKOYRBohg==,type:str]
          policy: ENC[AES256_GCM,data:vNUCO9BT,iv:3kfk1ewovYjHUYxN0usUhouQVvsoTTe8Sbw8UBjb0eQ=,tag:Oi8AC67diTgbziV7E6rUlQ==,type:str]
        - domain: ENC[AES256_GCM,data:NN1I7UnCMTXMGLU=,iv:y2ki9kJCHWKtTaMxR69cfm+Fdo6xyQcllAoFJHvnLoI=,tag:ltL2L7ExvRP3RAakGdym0w==,type:str]
          policy: ENC[AES256_GCM,data:vNUCO9BT,iv:3kfk1ewovYjHUYxN0usUhouQVvsoTTe8Sbw8UBjb0eQ=,tag:Oi8AC67diTgbziV7E6rUlQ==,type:str]
session:
    name: ENC[AES256_GCM,data:08GGTNs6mqylQQHwbgEf7g==,iv:0pczCcyByS9zxpoy58md7uRQeJuyqdtEWa8yVGWhjGk=,tag:qzx5tCn4DaFcngh6x5jUjg==,type:str]
    secret: ENC[AES256_GCM,data:O382bHC+NWhHnimZWiAhwoXLw+TOwkqR4vbNDbrrJZ+viCqeCoGfodFu5NLYBLM=,iv:JT5TaXqIVkHlYk7WE5xeEadTeaoBGEtKhtlbasETmM8=,tag:DL01S09RLsmd310RGpdzVA==,type:str]
    expiration: ENC[AES256_GCM,data:Mr8CbA==,iv:5mGYxXmq1F1EcVrdx+uQg7E5bQwAsLLf4aKKlh8+ZTA=,tag:vdxXXZKmj+fYV702I/IIug==,type:int]
    inactivity: ENC[AES256_GCM,data:OlNI,iv:hFghnTgc16vufpl+ohWtVDoLqpEv1gTqMi5ndRHas0Q=,tag:MVa/bnFfsC/Ckk9OmXgBVQ==,type:int]
    domain: ENC[AES256_GCM,data:WyeLTpcmC7Wx,iv:0VpiP4iEmyl1Gk8iDSAio00L4zQsT9ysvCnNllHDcT0=,tag:fRrJH8mYyMES7lPSLcqMjA==,type:str]
    same_site: ENC[AES256_GCM,data:f8L8,iv:cWVFtdkNrVU0EKAoeU6tQLO4C/sDyLjVlZ8tgfVV+Ns=,tag:fmNkY9gAPITrd3AehjdD8w==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:HeYP,iv:NRIbqt+E5TWvWC6XQfwWAr9k276VfBpxMWnsy6UZFVw=,tag:BfgChnOViKk2cj534M6XcA==,type:int]
    find_time: ENC[AES256_GCM,data:6zib,iv:Pq+ZCIowgovKveZ5lt1krIWw55VKHewOdPX+tRldKnY=,tag:NB565xmVSD5IWnIBHDpZKQ==,type:int]
    ban_time: ENC[AES256_GCM,data:EC2Z,iv:ya7O603Iyq/60NthhN6sYmVBXm6RXH0xvoV5I1nVzX4=,tag:GRxaAy8xGH0tAquE02/vmw==,type:int]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:/ESCjQD4yE7fWTwHgxPk/rqXm7sL0YCps4Log2XzsENPzV3N,iv:+Erx77TERCnTdx5xdwWrOPw6uoSfSj74mIoKyTt7FQw=,tag:n75ttVV9jANfOET50j9WuQ==,type:str]
        issuer_private_key: ENC[AES256_GCM,data:Lv2+3kKMjGLVI3vtrcsy+nQWa3B+SHs80+6MI+v3Bgae52kikkz7ieimk9PXTITGJa9a9yDhpVz7UFNO9idg7v3tKp3jfMyhcqp9k908xnR/3ZGmP4kRnqNsUvlhMCYXdXg6h20xlIS1elIIiZijJgQ67WAQ+gVHwqxb1LIgpgjuqeftPhg2YvUChHZrIkbw/oIjaoPRTkYaODoqP1cqSpG/rMTiRhRWyLv3f26bPSArAJXOes2GRkJ+2qQnbBz1XaK3x071dopGR0pC/gSLB/HO/THUfa5IRj/IEHHmofhrwUYkk4qhAXtepnY8F4+Zu4OhIypwaTvY/syBAbWXj1X4mSly5OprHLAsnnMWVxM/ACkGt6MsFd2q7VvNXBrD0Gi67qI4zn4iZUpeYTVuuLqCh4mXZAhkJyrGgAIxwiHHyHS9aYYkzcFqUvFWiLg52XPo2qH+t+fdNLMhaM9x+zmVj3NSZRijb/DHiiZhFp65I3azn00wBgVeSErieg16wARgKmBWyRI4YzeP2CeWIZiPtzQAhlW+aIBKmeIFBWxgc884MpQ9IW6UAhAHKahqshvq5IMCazCCMgQcoTxulJhHg0dZvaDTHWJxpXrw5fka16XfjbL9yYOnY8NPGeFeztauDrT6LZJVZLaf+A039tRZjR7+HhCRp3EM/7/RCTA/VpQzb5Hd9IrefE4yXKv+J8C9ykIJtd3kncl0CKKS2pyFZjR/c0w2D+nKKs3ygFoNk5FVEUUZ0pff0pKZecSxA8DZyIz5ip4pyLmGC+JcS1AYHAdGuWMWhjb/Dq7O2+Kq3H/rRjR3gsjzCTyBq4pGlFHIDn+DcuMGiUlL5mLWl/ajnd11LVmoQm+uKtmnXvmI8Ti9iZdZgzc/V5bbd47NxyxoRA9Bs1ze8e3cpQqvV9XZgkQhDy7zHVLePbMDXRzTumZFIlRWO9r5IFb2uN2BvGBW6p5YksVRStcqgyESEVw6+xVKYFbZNXhysHqu8vBnLSnFmXHhkYmZnl/WQIgGf8dCYKiBDqYO5yBUC1OkKzvuVTmMJMiUZ4Utwfpp8UWXyG3PLaKoNaI6kfVGX7Dt90zrObLp4f8HjrFmESRyo+qYUx8BS5VNDkp1bOn1ocUI9L7Jt0GvXNptlKaFwcBO4B98CK6Xp1IgJ0qnpS2ZdkDeBfvR13+Iy1WMj6riESHhRjZYg/w2jKDVwJ6rreGgsi9LpTD1F1RUtG/hIdYH5GyAFkPPoCHSY70ii7t4RwfDv2YXuBH5MTMtgE4NGBGOKNWNImgvAeg56+iZXTF7umqhfneZsBNcCG8P6FHSWK4xmNI+2gkZ+74NhOUYlXuR7PQeT5jZfUzfXLRPwMVZE/1J8HgSqKRGpwrv8BBmFFoy0XDqpf9Ut1QZ4JZ/XvltaEjcdRQh85tleRnQEDrpe5f4EWLdoJMUQ5o/qsPU3K9iUD2E1Bklep8JyK/ajmMS/+buLV7eUz2Ho7qt33Pmli+9dCTfiESDfOCoYMfHmQwv/LBBR1nxN2zcTxyIPC2rZIFmBiUkkZ/kSVxlc4A5klGhaqzQjUbps2UEtUggJLmm69w08/Xg1emO8w6ibzIjQAvEGRAe6DoVsiBpUI2ryrJKf09ozcgqweIhTUIXo/E+IcULTPrPPK1uJjNjsGt8vUKlP4bCCNpn90RDw6deg8Er1ViOBqIC2bgtgxYh/1sa++d50B3qH4ZLbLfcsPEN+I3g5xXVbWSqgXbNDOs1ZnyQFen99qNcbEThwnT5dQanqhgRIyOJe0pZFUsFnT5BCq3+jnKfPVDo68xiP2vq9JbkxBx2EfnhxEL2Kv8NZvdZIYFAjlVvkB46TMlb5DHgjJQyfMr2BOMi6J64xX6KJcYGYwEeiXFtCaswCd9X4pm+tbyYWnPA9VaNAYI2EBkVoWS3hHeZkFqELXi6L0SsZEWCtOAr6g+WiROAw8HkRY7vnztWPLnVeGPaXOK9ixNjepWrYbM87kkWQYYnfgoPmzSYtPnrl14m0s2FlzcVfVSAmLhku8+xhod39hoICXwOf5iI9F8LgbVusCDSvMegiQN1W6drvhdfeVqSfl+SfTspE1Th/d7cdVbg9xZgvSuLEIq5pe8tSgRiK9nH5VJAgGNJeFj+snjrP/Koz6AWL7Lpm5gRonCYlMhyD1H8n50NziHTiJAai0ZKcE28l2EUrpQ7aoFsavpJH4kH9vouGcxolm5kIEb+Srms99DIpWGgsdRfAmkiBXnFBAsY+cyGG8z+WUJhK9IK,iv:FyiBYbJ3188tM/i0c+SIEik+l+w0wCavLYh1UaIsLQI=,tag:ofXdnllXL1iUGZNGEu37wA==,type:str]
        clients:
            - id: ENC[AES256_GCM,data:P5eJ8ImF4nxRSJ1L,iv:+Kr7L954o0ZVp7OdgoOSaJXcxtc1dtqJ5rNCJs+1DJQ=,tag:8v7WWMaEJmj8Il4H3QJugg==,type:str]
              description: ENC[AES256_GCM,data:ifyKveZC5n4VlG+J,iv:TdLWc+qGY9tRf7/Pc85pCf9g1eDavWL7DNIbJG+48wU=,tag:5g9gA2UmBhUPkevALjDMxA==,type:str]
              secret: ENC[AES256_GCM,data:TdKCAnQ4ktjm8jdVs+Osw+GacjH+27j6dM8VyI3/s4JRKq00wi6mReXOEZmDqm0FEJ/+ShIcKRBXgh9UW6YKSb/iWgqmlmgW1Xb4BhrMslLw+KOr+DZh6hAxVfdGDcsa6Y2USevPJFpYhwd0asBfGfLRyEsdy3Dx8xburj5Ak2phhTk=,iv:7DoxbXL2uVyyAObwzywmgK/baISLdu0OXaE581cScXM=,tag:VwR+iTFiYvxpZtQTvgIMnw==,type:str]
              public: ENC[AES256_GCM,data:FRjduRI=,iv:jXkA1OBxHa8et/Heq8vVy5LA+Ezk4Q7nPMZ0FKt96G8=,tag:CexLAv+7qjjsJYV7er2e/g==,type:bool]
              authorization_policy: ENC[AES256_GCM,data:2vircYk68yTQuw==,iv:t0UhEEmmujwkaHfl5ASHZQNRGnjJtePlR+petyzjwGM=,tag:5+S/6qOWZWBfV6rFKNfoDg==,type:str]
              consent_mode: ENC[AES256_GCM,data:gD63nItWRR0=,iv:RnruhujimU63AytxwyyavbP9ehLi11yneNTUBAWWWeM=,tag:r2q3WbGY6/ta3ze6UfDPTA==,type:str]
              redirect_uris:
                - ENC[AES256_GCM,data:8XtD0Ut2dbqXFKzNQddJDu/ZuV5YZCY/d/P34elWGjKY8NfSQw==,iv:JXSRUIQpaZ78UK5QBVFCVUxCFLjKqCvfbIqqPbkFB88=,tag:Q4FiGqCcssFfPoZiN2l8pA==,type:str]
              scopes:
                - ENC[AES256_GCM,data:cc6sTFnc,iv:OrIV8JWMiSXxQa2/8ewlo/JG1aTvMl4+Jw+mSlzufWM=,tag:HmRMPmPuMgdtvBSJB3KSCw==,type:str]
                - ENC[AES256_GCM,data:RYJSZft4Jw==,iv:xFnbtrJArSY6MtAieamJO25M5DouNfwm7VPWl5AONPw=,tag:9zCFoIK0U7cw2E/Kfyg1tg==,type:str]
                - ENC[AES256_GCM,data:fF2abmDb,iv:sWVIGzp6hbhYBBfrINLJnpxXzlziOZ7USuaJaBFmsh0=,tag:YT1xg+yd4ZO9G6vLa+QkHg==,type:str]
                - ENC[AES256_GCM,data:nZ6aH6I=,iv:/5MWWkVueTaXG/hPCXND/1c8cVN0i6msACpsvzWMGlA=,tag:alwhHPoxQBRHYyDVdCtCxw==,type:str]
              userinfo_signing_algorithm: ENC[AES256_GCM,data:VognDQ==,iv:5C4SxGwZFaejli8NJaA2WrfbZUZqYvo6IzX/8xW6nXw=,tag:yaP/Znv32qigav1V4JfSeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19txs0a7xl89m2f0983fn0k3szj78n3tcjv8gddkvzk72r3fwsa3ssw0clq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcVRURGdmQ0tqelpISWJ2
            WDNXSHRGaktzZ21odmJnbXlhZysyeitFeVhVCjMwbGxBRlVKR1MycXlLMHlLK3Ny
            TjlQUkx0M1pUT1BKb25JSkwvUVJJbkkKLS0tIDFjVjhES2tGWU9sbkgwbmYvb2g0
            azFYYVo2K3pPa0x5aG1LNXp0ODdML1UKp5S9EdOydRfAgDDbf0gpMHs3v+yl0krp
            oE2SJUY3CDbQP715uuh6oESE9u6kOaOpxi7CQsZIUqIFIi9/k8InaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T13:37:20Z"
    mac: ENC[AES256_GCM,data:bneoxWsh0jlUluljkZZFHdtLsyIacKt6pfSMMeU9jwCfwgh+mW851lsMjYsIYJ8RRoNNZihEqlqEdFzOsllu6fYV30KLEugY4x8RFz+9BYzsNyCkkvHyN5ME3WMaaXOj6bW++msABtUHxWrwzz34BJ3Xvxd7CR0h+bOEgCZLZ0c=,iv:Ppw0oVuF9etTcZSWtUFErZqeyCoae59w83P3oJ2rJyU=,tag:EEonojV4AcQ0EyzYaBnycg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.11.0
