server:
    host: ENC[AES256_GCM,data:Li5E1ytsfQ==,iv:4iEXlrcfWxa0GqCj1omf17oXTopjx+f3e6oISDCVSVY=,tag:HrV+DlgUMCdGmeNBwpLwNg==,type:str]
    port: ENC[AES256_GCM,data:P0rkkw==,iv:pBB+/bVxHmX7rsDOU1SNEmh+DXYelzD4xyrEpRXijUA=,tag:xlFaN1vm1m8yP2YIxSUSmw==,type:int]
default_redirection_url: ENC[AES256_GCM,data:6EbIhHv2FOeCLipFaTyRcNddq9l07KhS4wf/KChMiQ==,iv:AYLXTEJU3X6joogOvXFrJsaAtFCrFYnkIKt9W6vAT+I=,tag:JooNyj/iHVXb4vY7cg0RdQ==,type:str]
log:
    level: ENC[AES256_GCM,data:4Pxasg==,iv:XLTpNOFxK+DnuPgPGRxKWsUrhcZJd8yJZiFW/ARPUZY=,tag:o7rM93ie51g1xtlkTqpzAA==,type:str]
jwt_secret: ENC[AES256_GCM,data:eui255VeWcd+aNuiN9+oqXmraBVIIKS5PQT4I8c5h+kOy5TBHeZABMVD0mzXZ0XdwRWyZVsXzfR9jDrJBsZmiA==,iv:eDVNaAzF/KXodTE4+cOmcAaCHtPDprmblP3qYxTbup8=,tag:o3EqMN6nuEB3lUrnTlnq9Q==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:Nk79qczN0o9PwTcSS709WLIb37clpZlv+OirfYGdoQL/zE4Qm8bFLyt2WG5PlMEFMN8dF+ZWhmBH9sGuzmVmzQ==,iv:rNOiuxcvQjL6Eehu4Mp+gElCq1EH+EPL2oRXTSsHat4=,tag:Oucmh0B2cSg0KzRZBcYdfg==,type:str]
    local:
        path: ENC[AES256_GCM,data:O7TyiCU21peY4TdUKvzl+w9E,iv:TFBuMWld4iLHik8m9UeqJ6tBr7bupsS/4wkn42u/1L4=,tag:3RRbs01thNoaUTCDmjE7TQ==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:F83ljfP380UiM0MC2w44IVthdHdNcbU7,iv:wxVi/VOrVGIpB+1+Vz+E8OoTrSyIbS/EuqjD+l/97GM=,tag:QOt8qNqqMfCpvv3NDUp9Ew==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:Sm99C19U0Yi9nUBd2TU6ZjZ3kWhJ5m7m9jg=,iv:J9TepdS9qaz9OUY9zuFp3XM6gTrD0Qwrw6l5S/7TqqM=,tag:TV1yAVCuSmG2OI9kBQvxaw==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:KuEY6jlf4xbr3Q==,iv:W1NmE8lcKcK2jUfS4+ZL1+XqVz8xJV9fBbv/pV7j4EU=,tag:ie5lWpbyqWMnaDmZ6jx5VQ==,type:str]
    networks:
        - name: ENC[AES256_GCM,data:LFij21n9EF4=,iv:11vgwnzHmOm4RaanbM9xZrNHzbstN3uXX8Xyzsl02xM=,tag:Zbj4EbL0ECbWtGm2puRRJQ==,type:str]
          networks:
            - ENC[AES256_GCM,data:DaVB+nQuLvfbXg==,iv:iqKqPOyef4l94MVrJ5XokOazOMwaXpp4aBDhUirGZKo=,tag:p15EzZrH55UcLrE52JbZeg==,type:str]
            - ENC[AES256_GCM,data:LnlG7b1BrWjU4nM0ZQ==,iv:quclnehnyh4C+Ctlgg67Y+Ld9zejFxXkG5OHIcMMMqs=,tag:Q5vXmGvjAAurZWuJ8jztNA==,type:str]
            - ENC[AES256_GCM,data:WCcm6gmskU4H3x3RZ7c=,iv:Ml2wXdEODBXXKSft2oFBzjkldtnfKWGTonEiyVpIkAc=,tag:fVIMzMyAMswlKWXEi+KexA==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:FsPSLFM/xLc9FYZmfxssQRRMArxON/U6,iv:2+n11yWBMQPBKX6kh5LDT/WolzQqfzlCYrH3lVgAXKI=,tag:lVxMv1nYfTUeYTOvNdX/aA==,type:str]
          policy: ENC[AES256_GCM,data:wq3R2x+v,iv:edcveh2Iur9L5wOpmXxIWpl5D62b79Wok6dLKcciSnQ=,tag:dRoDx1ESjhDw6AjrsxHRPQ==,type:str]
session:
    name: ENC[AES256_GCM,data:cozhk9mP7T7clo1P5J/aCw==,iv:YkPtRBdcXdHyx9Rb/23sf37+NTv8J/MaesOncIiBdN0=,tag:IrSO09FEfMUtUjndCqpAIQ==,type:str]
    secret: ENC[AES256_GCM,data:a6uyjNF8EzhgkSvqh7UVuzKIFyP7f/FglKUlU/3R92TbOKN+NXoLnA8YqqA83301vdo5emQAhMo7+nvFL67VEw==,iv:7BTEFR8+3bp52iUHoU0qCKPFeG1lTPLhbHrzDjIUXU0=,tag:BsdLOSYoM7KYRUFFBaaVCA==,type:str]
    expiration: ENC[AES256_GCM,data:/ONKgg==,iv:YvQnIwA/wFz+NT4fsyyOzUSBdPallzM/g0vrUUz5BPI=,tag:yB3tjqNwCHYvXQKeACoEyQ==,type:int]
    inactivity: ENC[AES256_GCM,data:9G0W,iv:+BSxef+K/pprEX5OthSNJfPimSZTSb8fLf/1HOznn4E=,tag:VoVLkK0GoyvEh4ZyvaJTjA==,type:int]
    domain: ENC[AES256_GCM,data:lCZev2ycpUW9Zz5k8OGrLPFhZSZgFw==,iv:jQdhK/VLLxgMOushqnqmGfKVBEDN49CRroDo9Wa4YdI=,tag:KltEpSMOYcyJWGrD7W24IA==,type:str]
    same_site: ENC[AES256_GCM,data:MvrJ,iv:Sf3jPmBnQC7r7x40uY2brZXFR5rx5GgBe4cx4GC3TD0=,tag:p3/ktJcgLygLVPjPoffdLA==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:g1w+,iv:KQ5yhFf5ht228dyuL80Yy+vdwUFM3+xZLwqEA6UMraw=,tag:DMr5l/i/0inENk7Nns+CwQ==,type:int]
    find_time: ENC[AES256_GCM,data:vwPt,iv:upZ7a7LmpPFjKJqa7DzRvI3llz4+i2Qki3FywrbaZOc=,tag:nXPZVvVYO9HthIYexcGMLg==,type:int]
    ban_time: ENC[AES256_GCM,data:ZeGE,iv:TV4SrGW+cL+cbP4prJZxNxAbGLsaKA8D4UYjcMBKhuk=,tag:wl8TNEC2VC4kGbjyi/0asw==,type:int]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:zvXUZy9/SVSIw6EQH4Cz752MgnexK6vaGjE+Q9R8dqj/FC5i0+f6jXdun7EqgAFTB5xzOObi2F1VWo8am4xVPQ==,iv:Q2qvGl6Oktl6u9d/tvqwxtjV4eBY0DOz14ScGcxaJuA=,tag:fc8irY6ZQBYu6a4rGgVqAA==,type:str]
        issuer_private_key_file: ENC[AES256_GCM,data:b+5Dh8eW9V/EMj/MZ1l0LQ==,iv:fYpVBrQEn01jLOxn6yP60hUhDGOsqEC/St6D0PSOUd4=,tag:CBuZ+iqF66d7UDdehvVF8Q==,type:str]
        clients:
            - id: ENC[AES256_GCM,data:s76hYf22FtAyYnnB,iv:qhXxx8NjKyTDY56ca8Pes8u8wz/EDZy7y/bx9hPLpe4=,tag:sAQmvHjLfBbs8LB6ULGIdA==,type:str]
              description: ENC[AES256_GCM,data:0a8WEiNXIPU8HsvO,iv:zoK598qG6Qi8sxsZAsZ+yh7Hs28xaVGWOQk5dB4DpxU=,tag:GBnNJ7m7aZzMb/WC2YINUw==,type:str]
              secret: ENC[AES256_GCM,data:nsr48g7SLneTcErkK7WD/7FSXcBLFX1xfYYgU/4hnX6q51sRHiHvQt+GwZlMKhExdzEVAeXCy0cKMFrvHmnqox/2jq/0gLiHzhgLgVU9Lt+7O+j1j+c44R6HmF/wdO9JIbby+VQ1/Am8kRQ9x+Q2rwVvi/Y+EJvlDEz1OcAgqgA9Wm8=,iv:A1/5ISY5iPc+dV7uAROQrSLUZGTKKrGayhIlQWchp/Y=,tag:/zDaYfVseDPurMXJfus7JQ==,type:str]
              public: ENC[AES256_GCM,data:IwVQU8o=,iv:gPyk7vA88iECHEviJcHV2o7Fe2TrXZY5CrF4TXcWjEU=,tag:SJIX5qnIyew8Y2wD0Fml9Q==,type:bool]
              consent_mode: ENC[AES256_GCM,data:OmkyqxrWDK4=,iv:tD7KBFmDYzpNcGkqUWB20g/+kVDPkIVYzZqTrgyhtfA=,tag:bx+UE7hUfFnkSX1XXrwlnA==,type:str]
              redirect_uris:
                - ENC[AES256_GCM,data:bJbXrnpXjdrxD19e2zkJQOzAlrjQlosjLCYVW+cHmxrddnvfpQtZNt8Ce7NOjA==,iv:fKsQEvqtW+yYZefRNuzX8/WE/BdctBhR0ZT92bI/riE=,tag:DUTB06PQ6sXtqd06A3JQZA==,type:str]
                - ENC[AES256_GCM,data:19vtIMP2n7tHndIwkDnmQUNh1TK07BMP/1s0uZj7T6HLRDzLQbFOK1/9RokPEKMPGYWEbwKt9hA=,iv:eRCejIs82LaU6y9RE6p+oFRvzyUQxz9hHxqbibgFUxE=,tag:4QVkUdGoWHKGBYNzfam/jA==,type:str]
              scopes:
                - ENC[AES256_GCM,data:Co5S45wY,iv:6AWIzKMTZHZa6zRIzUHnY0+AndIYxzZe+h155JeuhPQ=,tag:bbRgt2FKf+ttKZP2Wbm8Lg==,type:str]
                - ENC[AES256_GCM,data:0tP6RUmPyw==,iv:jeWxLPUqPzkk4dMUY+LZwIE6GGl5FM/lsv4ZRE2h6sI=,tag:qsJ+6+OniX7LswnyxFyUqg==,type:str]
                - ENC[AES256_GCM,data:F6YEE6Ow,iv:nIxi73as4RxXu7ae7Wb8kBx8LdzwYpRnTqt+FS6EjJE=,tag:EJb12ex3VjHGrVxyPM2wig==,type:str]
                - ENC[AES256_GCM,data:pR+8z2w=,iv:SVogeYiW+wXHMsnSmbVQzESyCDpyIxZZqAPGyoq9ovg=,tag:S7eAa5624K/mSKk5N2mVWQ==,type:str]
              userinfo_signing_algorithm: ENC[AES256_GCM,data:mNoJCg==,iv:A31yhTSh9QGwy5CDeTimTgicmBJXFV50lk7sbQYsZ9Y=,tag:qb9gcX2bbTsohYxHlDyPGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19txs0a7xl89m2f0983fn0k3szj78n3tcjv8gddkvzk72r3fwsa3ssw0clq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUkQ4d3c4RGlOOUM5VzNp
            eDVWK0dlVjJlZUs5d0srbVhVK0hlY1pZQVFjCjdIb2Y3bTY3cEQ1NXk3RFlqSVp5
            dFJ3ODJMTUpoank2aDhrQzh5WW1Qc00KLS0tIDFqNmUyVmhTVG1scUF2UmROK2gz
            aC8xcGVWMG1HRmphTlZ4am9HQ0FRSDAKvp51MmA1gh4iNLEEGIekkEOGphfdj//y
            kWEXFSt4j53+FsgDbrDRlbma4lQ77+nuFd6XLr6HJ9KxYjn/NgCUuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18y6d3jk79rvl27k6ux4fprk45rvfgxyux4a9wxjdsz3cstvecv0qcm90j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPY0dqQzhqOFJrSkJlZ1Vr
            WUtJQkpVYnZ0ZFdVOUdRYS82ZFd5K1MzUzI4CmtRZ3dYMTJyY01mRkc0OXlFZCtY
            a2pFdWwwMlEyRUE4clFJN2FvR081NTAKLS0tIHp0Z1VXOERYa3A3Qi96SUJvMUJE
            U1NmT2dEQnVZZkZIQi9KdE5oNnRSa3cKxqCxtLBYZYj4ETflI/XsXOZDreSbLHPy
            sZgG2pS5ZsFmfwHba0oEpUiTCQ7HJlKaLaK/Fne7a6EqvqnF3Mu/Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T01:09:21Z"
    mac: ENC[AES256_GCM,data:vqJt5RD7Psu63YrzK6EGmuDe0RQz83MqSRosIMtFOY5XZ0G7xPhqgkSn3apBMAZPeQA0zMqOQgm/dj6H8QK+FDp+0EieDV8DR1lEGIQx3hqrcKSqjZ59BsMSxwckyVbEMDFxw9x8luS61dAyDda4qG4mtG/5WhFpjg6KoWtMQ8E=,iv:OQE3nYrxhAWHj9S92oryli1zxEEhbRpALKzayIc3h1E=,tag:AkD8xvawWk71vYQV7L+QXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
