log:
    level: ENC[AES256_GCM,data:HLodZg==,iv:AHE2Dwk4fWtR7da+YzR0/WyuUQpCEZBpIoJcyz3K1a0=,tag:sQzXp0IkmdTLIEMTbIK2RQ==,type:str]
jwt_secret: ENC[AES256_GCM,data:veRJtLdB1Ypi67AE7gtGDDhftr3tNoXhzM83mIUDJq0XpTUIMGSZFw7RmjzTQvvPCn09yMt3RHF0EOcPyfkY+Q==,iv:f6Gh8UxAgOiSW++9b4Pq+pH8KHUdGQR8WAYks3ylziA=,tag:7RA5wCsO1RTOheDo8FJ3vQ==,type:str]
storage:
    encryption_key: ENC[AES256_GCM,data:PCyTos9tPpszqEK6neG3BgxwLIT1EWByHN2o3E+asW2I1nAcERViGRv1Uvap9cWWcqTQOZkWAxpnNhP8tU/3kA==,iv:TFlgnX3N+BUHGOfJr43vLzkytIVpMl35Rg7EZC+U5E0=,tag:1E1j+o3KD5Wo6Egsb108HA==,type:str]
    local:
        path: ENC[AES256_GCM,data:M0X4zXJVXZiNVxGCZtK0hz6H,iv:gwlozbpsCiWjYrBNjIwEhsjJ8sgLpbaamgu8zf2hD88=,tag:1a59LMC1xDzskMKmjZx9pA==,type:str]
notifier:
    filesystem:
        filename: ENC[AES256_GCM,data:71mocpVrJ5jJWxQlvyxtu7aA9/2+XnxJ,iv:c+FpcxocomG3z1Efmn2X4teP3sMNw8R7fOlGYVnVNf8=,tag:FNvPAR1+b13PtvxTz26ngg==,type:str]
authentication_backend:
    file:
        path: ENC[AES256_GCM,data:L7yrfT9f+nvwkiA2LeqotIE7szgEERmte88=,iv:hqfkN/V1AWyhxRW0j8I0ZFjShChANfpsATtQ7i17RWo=,tag:6HR8UA7YGqk+A4oKkS0agQ==,type:str]
access_control:
    default_policy: ENC[AES256_GCM,data:iNFmyqjNFgNaFA==,iv:t4diXK1nAjTsndk0RxUO8k6AXrTPV6qek5NUx5QeXdc=,tag:3Yhsz3CJ4WnmcV3kMZgjyw==,type:str]
    networks:
        - name: ENC[AES256_GCM,data:P3ksKk0bbyk=,iv:Or/6PeB1IgpWVMaGXD2xgDJF1+lqYaTmLrR3ZSwwrv0=,tag:BvxTJjfkBktDiCi7FP/V+g==,type:str]
          networks:
            - ENC[AES256_GCM,data:68TPNJvP4+jo3Q==,iv:iau6FtBZaHVKthQmOnCfyRrkHWuI9NJ6O+BGOc1pC/4=,tag:GXETGMTv88wsBx4LbaEsqg==,type:str]
            - ENC[AES256_GCM,data:HYqYI7oYMEAGZTs3zg==,iv:vS4Y2O8pbvonsnh3bB83nBU8N0v9dDyiYT4QpqXIbYA=,tag:jcvr3xZn4sF3Ucep+E9qzQ==,type:str]
            - ENC[AES256_GCM,data:/FQuXODAkUVxW18RVsI=,iv:hLu1YmiFrlu0KDhccUZEtlK8XyCi0hSWumMcBO1B2LU=,tag:OXGiS/u3xuS5Hq8WwTT8WQ==,type:str]
    rules:
        - domain: ENC[AES256_GCM,data:TpaVY+HPE1k+Nng4SlJojvCGnm8lUGxa,iv:Yf6K9WozEI6Ke99ZRtiSK6kuFaYfwpYuzHoWFmRXJzI=,tag:fhHpPpzkSNbUFgyxFEBDBQ==,type:str]
          policy: ENC[AES256_GCM,data:ZyBLB6/a,iv:8KlMghU81BD/Z/41jeuli4MMNBmGMTAZ0Nz7VgD+pEU=,tag:MQO54JtDb4gwj8ByjqSwuw==,type:str]
session:
    name: ENC[AES256_GCM,data:4eNOvJXZkY+q1YuJNfrInw==,iv:vp50LStQqAZXTep6CHU+41PtKs0EX4n01z2Gd7xXi88=,tag:V6MziuCM1xjHiE/HPV0Ctg==,type:str]
    secret: ENC[AES256_GCM,data:aZc7Kn/NYoVPtIvD989Dw0svC6qvLcmzPkZvHOvqPAu9a2yptAeLB4INoblPRo2JcPf20FOMvxKZnt7G6pcaiQ==,iv:t47XPz0lJM1KBW/ATMvRKgxB83gw5i0fNHH+8WN9Kc4=,tag:ZSzXd/Y7ao0sjwLNLxQlXQ==,type:str]
    expiration: ENC[AES256_GCM,data:TYjIkg==,iv:JZjzl2UHexUFsYq+DbAQs0AKIo3XSAtlZgb5tQJHzHw=,tag:sjsxeiMWRdwzdveqmmM4MQ==,type:int]
    inactivity: ENC[AES256_GCM,data:InKY,iv:lHSzCF0LO+ZMdAFdCWwpqeXaLBHrD44b+++agHaXPTU=,tag:5xb3zVFfCoPydPzLb7ICmw==,type:int]
    cookies:
        - domain: ENC[AES256_GCM,data:MXpgLEyKrNVvShLmJdgWDPjSy+jRwA==,iv:jepzWRKVBwQvLhHz8yqDZ34e8FdLjTxRPNHRVByQyQg=,tag:SY4gx4PXzOMmpxAWu4VCEg==,type:str]
          authelia_url: ENC[AES256_GCM,data:XP2wOLlW6cnzdosJEhxIbrBMQ8chUOL0JsGVXHKD9B+fGxeV,iv:9p/1ADfTTZYxfvg8GRBriY2rZlBcIo7Gbdy3LzNyleA=,tag:Scx+1R1Bf1RepOLZ15Qn8g==,type:str]
          default_redirection_url: ENC[AES256_GCM,data:ldpEzLiHXHtKuxAxAWRPmP4cvQR0AkhchEkhOtz5+A==,iv:OurZEvKKl4TfYRt4o8+XYR9XI4CRWC91UcKHAvzRizY=,tag:cfhbRPKG1QsjZQA3Qk/Thg==,type:str]
    same_site: ENC[AES256_GCM,data:Swq2,iv:FEvV9cU7CZRzpr3ZN/+CIEl5qUdrKM194Xe7QWhjcAM=,tag:HjV7EsfMNjQv3KWEA6xcMg==,type:str]
regulation:
    max_retries: ENC[AES256_GCM,data:QiLw,iv:R+RbzMa3BYwWJKvp7JEpjqiZGfSK7irHjueaO1jjYtU=,tag:xmwg1vIwXwZdW8U3frSHhA==,type:int]
    find_time: ENC[AES256_GCM,data:Qe+p,iv:mqgEzG22vIdFfxPgvV3nfa68jbkiMaghxd7qSVSCpOM=,tag:TWcStgr3iFZ7z+jTEF/tYw==,type:int]
    ban_time: ENC[AES256_GCM,data:oLDw,iv:IwYySZ+DM22aMXOELlHQ7cE/ZSMxDwg9SyX1BHBIr+w=,tag:JFLrAUMuRwNWUpm9gPXLnQ==,type:int]
identity_providers:
    oidc:
        hmac_secret: ENC[AES256_GCM,data:yPHLkCGNOwX1+i5l4qn5BVIPhdcnsKdg7FtUHfmBfCtpAZJD4+cNZYUtMtqjwN2Vew8YOegAb202fwhAZzMYvQ==,iv:RZLdxYNN8A0EHMiSjMYFyKDDAfsaFJMHQdHbjJ0IgxI=,tag:O6GEA7ZJuL47sL0i3fMxQA==,type:str]
        jwks:
            - key: ENC[AES256_GCM,data:waD5z+ujeKUjCkgr9196DMIxVKO50ZB1sZP23x2sLZExKYP44rWh1XKlfeRWNgW94mRIcm14sK/xdELT4pDcmTwjlK1HYFKARuUB+ZrRz+4g6gMEfw/yXAwp+GVgZbh3RXZ/Ix0QpiPZfxBi900nmnjEdyGZOuFT271khAjEXilx7kFXkKbN9lvVDYPT73QBZC3FCihIgLTLcZdwG9P8M+oxrMirhxhu4HPxxvei8uweUO4FscJ87OjEpJOpp+bHNRx+DrILGHr4gagv+BNwPQUBd05+NeStuDxrCuC9OGHeIAcL413OumX08AwqHIDuqNYE/ut2xCZYnJJngJAMFQRg1Yu0RPoP0TRrNIEfQCdmh64CfCx+1I/mdApdUTVkqrmfypdNZJVFxawiokF5MOV5ZRGeCTSzmL4MKFgFHYu2BfjWQ85uxiRW/+twFJokNb45zIAPOXiVhmKxJxwRGC4kILI+XDrb5CEllBC00GQlsuIeYuTWQV3sMGT9l7ew9eYwaQ9TSIEGfQRwjETOMYKSMKCfcEjFJS3THihcAM92m7Mf00eR/4quvxP3poVrqhjK3vcokhgXmGyZVd0t2DVqUooI8Hpxwu7cN43y1HQ6O6quEkdFm/4iYnJwWQ+pWzd7oQiZjvqGlQFp3AC0vHEl3X5zkyb0MpYGtWFVMZYYzcxXBB75yLvSpggoUYRz7YQ704nipInd4RRewsf5jw5kREjTtCTOQsa+RjT98dwg2Z0sSKDsJu+zB1yBZmTojSAl/BeD3oVpqRMMMp7OQpRvghNXdxZzkRUcjfuzYX5/uBlhI3da46yxZRGg8kRodgQXXbbt1RwBCjp0xJKXGIqvpmwnxdnZqF7AjmSzVv7mOe1GvI2BCTu2zstrnC0QxqOE/06M7B/f4jlkb2ZhTUTAxCLS+6GWZ6zAdLzzvj+fbapodfoI4GntAmdqi+0DjPI6dRjaeZ82NUv3F23UVgGZNWodRPVDDdxRlpgfS00RD6E6pgG90EW8OZTHFHk/VY4zM3M2Ex/Vvv7FIj6Apw2WA/4mFLC8v5Z5lTOhV+8evL/IBgEjpHw2+ydWVDSNTIaimtaAf9Vx1ty068LtcWSTVNgUezfop2LJwPe/WdzYmP9sdCIoJEEPV29h8WbwqsbYfxEGjesSMuLFOrwXkgo2Y5mxMPoxiBnCT/VnOugAm+Pr012dG/5Ex0gEWqabxQtfs5UVyFvP9iXS+Rz0LQXWbLjxmKaYXpmBExdgt7Mef+Hv1bKt9cGCKSDNaRmoduZqdwOqm9ugSYAqxjUZiY3QSJ/IzF6QyBzAY0xJhlF61Kn162gz71z/RrD9+UBulh/Kax8b3egczQ8X7sTjx8/UG2ujtBVvR2DRrHo9ZSVOfRoPRoc3uIgWo7ePa3HLZhdCUNknli5B/GJaL5Yd6/YBeUpB/azitM8AKFPyDreZaaxuEBVIeTGxEbXeqWgzuubrnmvNrajim1/1PMnWK1Cx4lJhrBPznzyTJ5LNylYNhKcUG5Z2i76J/YCyDhoR1nKsk3HFf1lskx8YaMl83X8vkWH8HR7tfMRzkPERiqQcPwRTLwpKmvhw8zSRcs1La4SuzVwkCu1w1ByEb1oTV16lsttkZvGJA04oDXp2q2sHyc9T0EZ1BNfkoG4lirv6g1WNapRshJBZwGiXxltiAZT2de9+/n9S/FRKKp9aLLg4V2lOdkcvP4IsAE77nkN+3y+/zlIq9D4lZZhCq3Lp0NSKRot6H3EN3v1rs9v/5XR+w0PGOTwZhsx3NmbV0dAK5ZGXMqLqeo/7SpJ+HEImASscGxUNwmQ5qoB90K9/agy9Jf8bryTEwzpJlHVW6BjB1M2/LoHhMSVT9oOGJbXr+4BXZ2BxfbKwi7cwPj+vGhsp6ItCA0HDTeZPBpgeaO7HKV2rIHlawp4/+ppEJscc8r54MyLgnTRNwDNq7I+WdKQ0v+osJMULsXIL03SLiMhl6T9jm6K/aKNzOR8c/qqGck6gsogxK6fVg4bJ5k/22u8UyDU4GyOPRkz088nb2Egi+tBsdvMg7bdrvKyYPcckwFSpxz+T6t52d4rDB4A0Xd4Jb2ZDX5SHSFtq9C1BzaMwer5sBeHbOVc7ooWIYvrChOp6YufVECSv0aKQJuCXK7q137iE0GB+kRAG3oob32uTKgQqwpG5mx5qsAnJ70rsnFNScChf/ZG6HNmpn3VTUZWGQ6W4Y3fz2Vr3+BKV9YFmTHbwUfyXOiuq6RGDuxa4v6Guy7BAv7FZ,iv:TS2+niije0YSEOk4gukcOd7Tl3XGDn2A4e624FKVqXU=,tag:FiOP1AceW+9hZHhEDk31sw==,type:str]
              algorithm: ENC[AES256_GCM,data:/sRrXB0=,iv:qJR8xOgk6JDXefAnAzmSDDWth2jvSlxLRxGXFqfAgKs=,tag:dN98EcvAH9vqI/2b7LnlDQ==,type:str]
        clients:
            - id: ENC[AES256_GCM,data:78qaPfPCWzbktHhj,iv:fjARXequE5z1FjeJdtPvtccLWQ8TXYrY7IztLPaYXGo=,tag:mzXYCUiJvq3r9g9W5ef0RA==,type:str]
              description: ENC[AES256_GCM,data:j8dH0sX8idsoG5Wc,iv:W+sLg7oYrwuRTY+d+JiDWPfTQJUE0GXz1vDQhHe6mz8=,tag:8GUok1dUWf1x8c3QXIoMuw==,type:str]
              secret: ENC[AES256_GCM,data:u9VNgFZrYXqyW7rw0anuSaMJ+8E/h1WOH/k91pFpkMyve652h+KH0Az1ko5Xh+bAU7OfIvFgkmIIlMTIhgE8JjTSK5qjsnVfV1VM1Pw/xBw7jWDiJcPL1t+JlcqICZLXjzrSMR7Cur1oBCzO8WEtk3cKthslnnE9H3CIn7orC95mLuc=,iv:aSojYMFFuJNBPLALbxEd27vJ/aP3+jwtxW/4Q6XqgRk=,tag:cIDRQjC0dz60KqxlYifO1Q==,type:str]
              public: ENC[AES256_GCM,data:cjWg6TA=,iv:KnUXnG3WeSqPdI6i/j5ueQRD7undVD2ChlxeqrN4KA8=,tag:dOuYAS/ceY6PNn+ZByU+KA==,type:bool]
              consent_mode: ENC[AES256_GCM,data:RolqZV10hPU=,iv:6qgOAZ6LvvIX/oOlT03qUMcYpiyYaIrSenau/dWoVoM=,tag:TwA9GJDAuJjPaZVH7VkPGA==,type:str]
              redirect_uris:
                - ENC[AES256_GCM,data:HrQGrNcks7IFUSpNldBG9WGdSphp/DZy4gCxl24sU2I1CBGSf58cCB3eGUW+YA==,iv:tmcMmEkb9mCf8icBHaIipJkGefxWcI6TMIMF0pzGRDs=,tag:qnJ82TogZd396PdYfci8og==,type:str]
                - ENC[AES256_GCM,data:3I4p3kAQoCP/moGTFvwG9khJ6OG+Y7PJ0Muym4bVfI6HFR8McJuMZrm6XDaOlN9x1R5byYMfOJk=,iv:OpiZO2zIssAXkLVKQwds3U0Ma2XfQ7T5y24782fWzuA=,tag:6yS5KkC64A7NGcFeOVS7NQ==,type:str]
              scopes:
                - ENC[AES256_GCM,data:Gwf9+5ni,iv:Qz+D19BOOUuSb8RM/0S8e8Y1R4JEZ2tzsqvRCpV/Hi8=,tag:90wj/4cDwAwzBLSK1dPpTA==,type:str]
                - ENC[AES256_GCM,data:qGO1r+BC/A==,iv:ROaY0GFGQQxBhtp3NUbYebaUwaWpdCey+KiDpq4wgqE=,tag:KClR0tw0uzBdJs+tU9jNRw==,type:str]
                - ENC[AES256_GCM,data:3eGt7Npe,iv:A4r4NteAyd1VfWs92GMNdYKBxAzD8MTSb/JGdc3n7uw=,tag:xsz0f1b7kN1WV6x1hr198A==,type:str]
                - ENC[AES256_GCM,data:IltX+d4=,iv:r9CPw7qaIS4hOm5sK54YJsghtsGeoQDmhauo3WnPCfI=,tag:mWQNSq+aQE2HsOePyaK5iw==,type:str]
              userinfo_signed_response_alg: ENC[AES256_GCM,data:jtwKyg==,iv:7vamW2odjaXLOsC6nm4SzhfBFbzk0mHhBCFw5LRyiog=,tag:Oph+GE3JUInAa3ZyKZDgUw==,type:str]
              authorization_policy: ENC[AES256_GCM,data:zMnn0DtbjXSYug==,iv:FpqTjpzcvuWTHT0sssT3h7PZFQk/InzTp5iMf/GxfME=,tag:KmONWSqZmYro4NlCNN7lUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19txs0a7xl89m2f0983fn0k3szj78n3tcjv8gddkvzk72r3fwsa3ssw0clq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa28rNXMwNlpDL2xsY21P
            Q01sM0FpQm9Vck1rSWsvMVYraEh1RGpHU0M4Cjc4Um84bnF2QUgwT29CQ20wWTBG
            MXhMUTlyYzZ1cmd6cXFpNjVzK2U4aWsKLS0tIDdHVXBpeTBFNi9sU1E2TDJybGVU
            V0x3ejhPOXdiYXZtSG4wczlJTlBna00KFnYSSWue5wKFfFQQ9oUJ1ND+++RrkCP3
            cdl/6Lj1YZ+faBogk/pBiYxjOGx2rmUa//ay0ebW6VOLkpuMRR0NqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18y6d3jk79rvl27k6ux4fprk45rvfgxyux4a9wxjdsz3cstvecv0qcm90j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKR2NvUWRWTnc3Vk4wTTRw
            UHVNbURKbkpjbmR6RUl2bjk1Uk5WaDhNbnlVCkJUWlMyMFppVElZamVrRHdrVndt
            MWQwbGxEcVZYRU5meGlRWStZTUNMYVUKLS0tIEpnSFAvOWdTYVdmY2lMWkNIcHNl
            ZjgvZHpsMUJsNTA0Q0ZrUDR6VTRLak0KXRqYDvgestkIzpb1cHhibY7w+c0BDz7Y
            mh5cB1nz3zwdI3wyCT8EWH6ZAraS06Gp9KYJ/xG0r9bTvxC0rTEzrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T01:09:21Z"
    mac: ENC[AES256_GCM,data:krm8ucZN6pSljo6hPB2+IUsJQHVU3UxKzTg9i9bwO4c1aP+CW866HzGllritrRe5odrructcHRpuG+RL6vVgXeubCquZlH98CZhmK0Mhx+OcE+dr8SZxBX6IDr4pdwg6IxFRWAQaCvchUnY0HA5noCNA9c2WpUt2xbtS0d29S1s=,iv:p7b8r+LXQkFvkhw9PsYji9nAR5qFm0PnhMm80z9mevE=,tag:0AyjTu5e41wxA9AcG46ISQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
