users:
    admin:
        displayname: ENC[AES256_GCM,data:pMj14nWxVhbTUQ==,iv:017bTsS3/vi/HkVFaSPDedHSGoG9uV22qMQtRuHoj24=,tag:mQUJcIbLMYhKs3T+pTbTBA==,type:str]
        password: ENC[AES256_GCM,data:o9ItNlVXjN8IvwrS1YkZACvU8epMyF+a1QK6iZOUiw9RXU1YSJBtZrOKPd9AN62zkELKMnYDAdDgaQF1lSv21OxVu9OUeiPMi2gDUmUeb5wXZYTFu7N2FPOa51IUhZe1IA==,iv:nNAGNp7lCYA4kgfIkIe75ZAB4JGovgeOhmNS+frBc00=,tag:saH5a4keDgH4ArSRDrMMuQ==,type:str]
        email: ENC[AES256_GCM,data:DBFO3DM6faoZEuKWhQcin0o=,iv:8nRPL79qQvVGTRoGIao9bz/KCkpo04nUCNsvU0XqSkQ=,tag:2ytfutfRDOod5jXgANrq7Q==,type:str]
        groups:
            - ENC[AES256_GCM,data:UTkpnfDV,iv:Q7fwjxmRGeut1NvuUvE0IRnbfs1plD8N6SsNkiodRQs=,tag:9oqgligllGob2OoQk8foYg==,type:str]
            - ENC[AES256_GCM,data:qrb5,iv:7kOf1iebRqJJ4+Qs3bBKvV0MnPBBOzja/fwy94qT5Ig=,tag:r3ldVYl0yVg1Nj1O8wmV7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19txs0a7xl89m2f0983fn0k3szj78n3tcjv8gddkvzk72r3fwsa3ssw0clq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQW50V1hJN1JxMDRRN1M4
            SWNCNURNU3dSLzBCaHNKenNRcUl1V3VBVVhjCjJlSXhpdTNPR1BuOEtodHluVVF4
            cnhDa1JPVG1CeElGM0JoWkRTSGtKZFEKLS0tIG5qTUdhY0pLMU5ramVXeHo3c0xU
            UkdFRnI4Nlh1UkRvaW1rcklNRFRzZzQKmGb31QgP2+AxU2SXtsPcm4fs/Lj0v8sI
            Bsqg3yhSUmOD6GTQen440YAu6fjNRXIYurvMyhoo9V/8fp3t6uTjPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18y6d3jk79rvl27k6ux4fprk45rvfgxyux4a9wxjdsz3cstvecv0qcm90j6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ2ZyYy9MNG9nYzNxQlZN
            d0VqazJZaXVFMTVMY0orUC9ZeGNyT3RWL0ZVCjZ2aXM5L3VFUEsvNVFBTDlmY2xX
            OE5UNFpGTXpOZWlzS2d4bHJGaVJrL0EKLS0tIEZNY0cyK1psNkgzRzFuUGF0MTlS
            QnhaSVFvZ1VMUC95aGxNWGFmcVFTZ1kKdBiXkuE9VucAIoDClef3IO6Y/TIQjM5b
            TRGOxgd3GBzrr/r42dshuSDC22QiQMHg7viktPV5f/O/JiSeaKkcaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T01:09:21Z"
    mac: ENC[AES256_GCM,data:UcvzVdZLi47IUqvsdXuX4prxWxrPZwNwif+XetYotWUZNI7rPq8DGsHQI+hA2Wiil0lw6rJ+85QhOdaaieFcad0Ki8ryyFEvQ5USZ7MR0TZM8st72p9zAtHVa63HG6BENV00A0U9BnDbWAOUy4+suZy5nJbl417C/OYiG/SuaEE=,iv:x4DwnpyV58BMZvuGszDBnLrX4CtAKPMTjTczEZq74Uk=,tag:4DmgHC+yiChoGzKDeMcyOQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
