users:
    admin:
        displayname: ENC[AES256_GCM,data:/u8cldverCKVwg==,iv:1k0g7tnbwzWtZqKu4Tc6z2eP6m6tzi9XtATBRjHsGkU=,tag:A4Om8yjpF7UaZ9VAmBj1rg==,type:str]
        #ENC[AES256_GCM,data:xdWEjkKKCdLz,iv:X0S9Dws2fNzChUksD+9OtIMjD0d20AzEIbGVRPR/L74=,tag:2oTqKhbVCxMHfrN6mt+5yA==,type:comment]
        password: ENC[AES256_GCM,data:VQ+GU4GljHIGYXP8Kh6WglN46Uf/70Lf3RRdu16dVgO7Jsk6QM3mrxBeP/DXc2E8R8KTxbreJbwmusyh6FHUZD5dS8xHw3vFVjy64l6dIAENHT/+P5xhir4V7SZTUNTiaQ==,iv:6lnaGqIbJIJU8uszbVEe4qqvUx7WLcrKatEEfq5gV2Q=,tag:z4R5DizxVrEXpF+uctMXUA==,type:str]
        email: ENC[AES256_GCM,data:eIapb4mJaojXWjl/Zkm9mOw=,iv:WP3c79373ohKBS6P3QHaV3nVKcCo17odmnBsqMAJnB4=,tag:ai8vYjfdLAU0nCS8iWitHQ==,type:str]
        groups:
            - ENC[AES256_GCM,data:TDEmfvIw,iv:qKZ7chiwOIqMo3A6UX/Cbu4NW7Y+7/AlBeOiWOJcDKg=,tag:/4BaAqzY7lqPT+qzzDsNjA==,type:str]
            - ENC[AES256_GCM,data:ty3u,iv:1wlRn0cAJy7v6kyAdQi+t7np/FY/GYNFKmDJzQUR16g=,tag:2xmZxYx/GKKwZ+YfBGyxYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19txs0a7xl89m2f0983fn0k3szj78n3tcjv8gddkvzk72r3fwsa3ssw0clq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNDdVN2sxZkdkT0syUjlC
            TlJhSU1pcHV1Snd6bUtXRnFwaFZSdGFFdkRnCjM5dHZab0dxQVlvbU1ocWJ0aVd0
            eXJFWUdFcmJETVVXQjVUbUY1ZThFVFEKLS0tIE9ZRjdsTVkzN0pnOEIrMEJLRHZF
            a3dOUE5xeDRPaE9JSllrWGZVQW5FcmMKxuPR6FNiK/IINg9NimxMrxa2p7zGGxA1
            QwZXTepvPI6RMHvfxHvYuePn+ZWiw20talG+44ku3WNwcyvkoCiEcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T13:37:20Z"
    mac: ENC[AES256_GCM,data:GqZ06oEnYVhrfpJJjklrltxYBiA5A0tyafw0U/1PF2/3Ls71d2QiB3OyfI8Eot6Bwu66OgRrXW455qo4ojZXS28XcevUeUuIY0MYCTVFzpXwn7qM40Ihc+/fJb7SHLoBvP/E3ptPrUA3d5+OTASSr7TmBe67uIsagK0FXmELGV8=,iv:EoYp0Y+sTAzlFH6n6hkSiM7WrDjlzosyd5KNHvqN41Y=,tag:4tw7BWz1FL5i8JW4yP/pGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.11.0
