{
 "title": "Docker Containers",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[1m])) by (id, name, image) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes) by (id, name, image)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[1m])) by (id, name, image)",
     "legendFormat": "{{name}} RX"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[1m])) by (id, name, image)",
     "legendFormat": "{{name}} TX"
    }
   ]
  }
 ]
}