{
 "title": "Go Runtime Metrics",
 "tags": [ "go" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "Heap Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}} {{instance}}" }
   ]
  },
  {
   "title": "GC Duration (Rate 1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[1m])",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  }
 ]
}